Repository TencentBlueKing/bk-nodeman, pull requests merged in 2021-12, with the labels that each got.

#297 bugfix: 修复proxy上的agent包等文件自动更新失败的问题 (fixed #294)
  apps/backend/tests/periodic_tasks/test_update_proxy_file.py
  apps/core/files/base.py
  apps/node_man/periodic_tasks/update_proxy_file.py
  apps/node_man/periodic_tasks/utils.py
Labels: kind/bug, version/V2.1.X, module/backend

#298 sprintfix: 升级 Django3 依赖组件适配
  .github/workflows/codecov.yml
  Procfile
  app_desc.yaml
  apps/backend/components/collections/bulk_job_redis.py
  apps/backend/tests/components/collections/bulk_job/test_job_bulk_push_file_v2.py
  apps/core/encrypt/handlers.py
  apps/node_man/migrations/0006_auto_20200602_1104.py
  apps/node_man/tests/test_cmdb.py
  apps/utils/encrypt/rsa.py
  common/api/modules/esb.py
  config/default.py
  dev_log/2.1.356/crayon_kiozhang_202111152019.yaml
  docs/dependences/to-django3.md
  pipeline/contrib/external_plugins/models/fields.py
  pipeline/django_signal_valve/models.py
  pipeline/engine/models/fields.py
  pipeline/models.py
  requirements.txt
  scripts/pack_ieod.sh
  scripts/workflows/env.sh
  scripts/workflows/install.sh
  scripts/workflows/local_settings.py
  support-files/templates/#etc#supervisor-bknodeman-nodeman.conf
Labels: version/V2.1.X, module/framework

#310 feature: 新增安装通道上游配置项，适配更复杂网络场景(close #234)
  dev_log/2.1.356/daoqgong_202112021456.yaml
  frontend/src/config/test-anchor-key.ts
  frontend/src/i18n/en.js
  frontend/src/i18n/zh.js
  frontend/src/views/cloud/cloud-channel/channel-edit.vue
  frontend/src/views/cloud/cloud-channel/channel-table.vue
  frontend/src/views/cloud/cloud-channel/index.vue
  frontend/src/views/cloud/cloud-channel/install_channel.md
Labels: kind/feature

#316 bugfix: 安装通道文档路径不正确 (close #315)
  frontend/build/webpack.base.conf.ts
  frontend/src/views/cloud/cloud-channel/index.vue
  frontend/static/doc/install_channel.md
Labels: kind/bug

#319 bugfix: 版本日志无法再次打开 (close #318)
  frontend/src/components/common/log-version.vue
  frontend/src/components/common/navigation.vue
Labels: kind/bug

#325 bugfix: 修复访问后台接口出现 JWT 校验异常的问题 (fixed #323)
  apps/node_man/apps.py
  dev_log/2.1.356/crayon_202112071607.yaml
Labels: kind/bug, version/V2.1.X, module/saas

#322 bugfix: window手动安装无curl.exe下载链接 （close #321)
  dev_log/2.1.356/daoqgong_202112071622.yaml
  frontend/src/views/task/task-detail-slider.vue
Labels: kind/bug

#317 optimize: 日志错误信息等UI优化
  frontend/src/components/common/strategy-table.vue
  frontend/src/components/common/verify-input.vue
  frontend/src/components/setup-table/install-input-type.vue
  frontend/src/css/app.css
  frontend/src/css/install-table.css
  frontend/src/views/agent/agent-list.vue
  frontend/src/views/agent/agent-setup/agent-import.vue
  frontend/src/views/agent/agent-setup/agent-setup.vue
  frontend/src/views/global-config/gse-config/set-access-point/step-form-table.vue
  frontend/src/views/global-config/gse-config/set-access-point/step-host.vue
  frontend/src/views/task/task-log.vue
Labels: kind/optimization

#339 optimization: 任务日志优化error & debug类型展示 (close #333)
  dev_log/2.1.358/daoqgong_202112131702.yaml
  frontend/src/views/task/task-log.vue
Labels: kind/optimization

#348 bugfix: 修复插件操作选择部署版本时报错无权限的问题 (closed #346)
  apps/node_man/handlers/permission.py
  dev_log/2.1.358/crayon_202112132135.yaml
  dev_log/2.1.358/durant_202112131012.yaml
Labels: kind/bug, version/V2.1.X, module/saas

#359 bugfix: 编辑proxy密码报错系统错误 (fixed #355)
  apps/node_man/serializers/host.py
  dev_log/2.1.360/durant_202112151606.yaml
Labels: kind/bug, version/V2.1.X, module/saas

#361 bugfix: 插件配置版本匹配不符合预期的问题 (fixed #357)
  apps/backend/plugin/tools.py
  apps/backend/plugin/views.py
  dev_log/2.1.360/durant_202112151754.yaml
Labels: kind/bug, version/V2.1.X, module/backend

#367 bugfix: 修复windows插件卸载失败的问题 (fixed #366)
  apps/backend/components/collections/plugin.py
  dev_log/2.1.360/durant_202112161602.yaml
Labels: kind/bug, version/V2.1.X, module/backend

#368 bugfix: 使用私钥安装P-Agent时，校验key失败的问题 (fixed #365)
  dev_log/2.1.360/durant_202112151720.yaml
  script_tools/setup_pagent.py
Labels: kind/bug, version/V2.1.X, module/backend

#369 bugfix: 表格锁边及滚动问题 (close #364)
  dev_log/2.1.360/daoqgong_202112161652.yaml
  frontend/src/css/app.css
  frontend/src/views/agent/agent-list.vue
  frontend/src/views/plugin/plugin-list/node-detail-table.vue
  frontend/src/views/plugin/plugin-list/plugin-list-table.vue
  frontend/src/views/plugin/plugin-rule/plugin-rule-create/version-detail-table.vue
  frontend/src/views/plugin/plugin-rule/plugin-rule-list/plugin-rule-table.vue
Labels: kind/bug, kind/optimization

#370 optimize: 优化js、ts lint配置
  .gitignore
  frontend/.eslintrc.js
  frontend/README.md
  frontend/package.json
Labels: kind/optimization

#371 bugfix: 任务历史详情左侧IP列表分页异常 (close #349)
  dev_log/2.1.360/daoqgong_202112161526 copy.yaml
  frontend/src/views/task/task-log.vue
Labels: kind/bug

#388 optimization: 重装Agent Windows登录端口自动更正 (close #363)
  dev_log/2.1.362/daoqgong_202112210958.yaml
  frontend/src/types/agent/agent-type.ts
  frontend/src/views/agent/agent-list.vue
Labels: kind/optimization

#387 optimization: Agent 安装弹出参数校验失败列 (closed #376)
  dev_log/2.1.362/daoqgong_202112212034.yaml
  frontend/src/components/setup-table/install-table.vue
Labels: kind/optimization

#386 bugfix: 跨页全选情况下安装通道没有默认值 (closed #377)
  dev_log/2.1.362/daoqgong_202112211645.yaml
  frontend/src/views/agent/agent-setup/agent-import.vue
Labels: kind/optimization

#385 bugfix: Firefox 浏览器粘贴 IP 解析错误 (closed #378)
  dev_log/2.1.362/daoqgong_202112211913.yaml
  frontend/src/views/agent/agent-list.vue
  frontend/src/views/plugin/plugin-list/plugin-list-operate.vue
Labels: kind/bug, kind/optimization

#393 bugfix: 富容器场景Agent安装脚本问题修复 (fixed #384)
  dev_log/2.1.362/durant_202112232131.yaml
  requirements.txt
  script_tools/setup_agent.sh
Labels: kind/bug, version/V2.1.X, module/backend

#398 optimization: windows脚本兼容性优化 (fixed #397)
  dev_log/2.1.363/durant_202112241718.yaml
  script_tools/setup_agent.bat
Labels: kind/optimization, version/V2.1.X, module/script

#403 optimization: 周期任务削峰打散度不足 (close #400)
  apps/utils/periodic_task.py
  dev_log/2.1.364/kiozhang_202112281728.yaml
Labels: kind/optimization, module/framework
