Repository TencentBlueKing/bk-nodeman, pull requests merged in 2021-11, with the labels that each got.

#243 optimization: workflow 优化 (#121)
  .github/workflows/auto_version_release.yml
  .github/workflows/start_new_version.yml
  dev_log/2.1.354/crayon_202110301727.yaml
  scripts/workflows/release/get_prerelease_version.py
  scripts/workflows/release/op_yaml.py
  scripts/workflows/release/upgrade_release_log.py
  scripts/workflows/release/version_increment.py
Labels: kind/optimization

#256 bugfix: 修复查询主机插件操作流水异常的问题 (fixed #252)
  apps/node_man/handlers/permission.py
  dev_log/2.1.355/crayon_202111042014.yaml
Labels: module/backend

#274 feature: 提供返回操作类型的接口(close #230)
  apps/node_man/constants.py
  apps/node_man/handlers/meta.py
  apps/node_man/tests/test_meta.py
  dev_log/2.1.356/kiozhang_202111171615.yaml
  frontend/src/config/config.ts
  frontend/src/router/index.ts
  frontend/src/store/modules/agent.ts
  frontend/src/store/modules/main.ts
  frontend/src/types/index.ts
  frontend/src/views/agent/agent-list.vue
  frontend/src/views/plugin/plugin-list/plugin-list-table.vue
  frontend/src/views/plugin/plugin-list/plugin-list.vue
  frontend/src/views/plugin/plugin-rule/plugin-rule-create/perform-preview.vue
Labels: module/saas

#271 feature: 服务器文件迁移到存储源执行命令 (closed #260)
  app_desc.yaml
  apps/backend/management/commands/copy_file_to_storage.py
  apps/backend/plugin/handler.py
  apps/backend/plugin/serializers.py
  apps/backend/plugin/views.py
  apps/backend/tests/management/commands/test_copy_file_to_nginx.py
  apps/backend/tests/plugin/views/test_plugin_production.py
  apps/exceptions.py
  apps/generic.py
  apps/node_man/periodic_tasks/gse_svr_discovery.py
  common/api/modules/bk_node.py
  dev_log/2.1.356/crayon_202111112105.yaml
  docs/workflows/release/api/nodeman.yaml
  env/paas_version_diff/paas_v2.py
  frontend/src/api/modules/backend_plugin.js
  frontend/src/views/plugin/plugin-package/index.vue
Labels: kind/feature, module/backend
