Repository TencentBlueKing/bk-nodeman, pull requests merged in 2021-09, with the labels that each got.

#57 bugfix: windows p-agent 安装问题 (#52)
  apps/backend/agent/tools.py
  dev_log/2.1.342/durant_202109031138.yaml
  docs/install/dev_deploy.md
  docs/install_channel.md
  docs/nodeman_graphs.drawio
  docs/resource/img/nodeman_graphs-产品示意图.png
  docs/resource/img/nodeman_graphs-插件变更示意图.png
  docs/resource/img/nodeman_graphs-插件管理2.0编排.png
  docs/resource/img/nodeman_graphs-插件自动变更流程图.png
  docs/resource/img/nodeman_graphs-策略抑制.png
  docs/resource/img/nodeman_graphs-系统架构图.png
Labels: bug, docs, V2.1.X

#66 feature: 支持接入点中 cityid 和 regionid 配置为空 (closed #46)
  apps/backend/views.py
  apps/node_man/migrations/0051_auto_20210903_1320.py
  apps/node_man/models.py
  apps/node_man/serializers/ap.py
  dev_log/2.1.342/durant_202109031138.yaml
  dev_log/2.1.342/durant_202109061015.yaml
Labels: feature, V2.1.X

#69 feature: 自动化工作流
  .github/workflows/auto-generate-version-log.yml
  .github/workflows/start_new_version.yml
  app.yml
  scripts/extract_version_log.py
  scripts/parse_app_yml.sh
Labels: feature, V2.1.X

#86 optimization: 支持使用CMDB主机监听事件触发订阅变更(fixed #85)
  .github/ISSUE_TEMPLATE/enhancement.md
  apps/backend/constants.py
  apps/backend/subscription/render_functions.py
  apps/backend/subscription/serializers.py
  apps/backend/subscription/tools.py
  apps/node_man/models.py
  apps/node_man/periodic_tasks/resource_watch_task.py
  apps/node_man/serializers/base.py
  apps/node_man/tools/host_v2.py
  config/default.py
  dev_log/2.1.344/durant_202109081956.yaml
Labels: optimization, V2.1.X

#133 bugfix: 修复主机类型订阅 nodes 传入信息错误导致 KeyError 的问题 (fixed #132)
  apps/backend/subscription/tools.py
  dev_log/2.1.348/crayon_202109181700.yaml
Labels: kind/bug, module/backend

#130 bugfix: 某些情况下suse操作系统pid获取为空 (fixed #128)
  dev_log/2.1.348/xcwang_202109161755.yaml
  script_tools/setup_agent.sh
Labels: kind/bug, module/backend

#154 bugfix: 修复周期任务执行报错：ZeroDivisionError('division by zero',) (fixed #153)
  apps/utils/periodic_task.py
  apps/utils/tests/test_periodic_task.py
  dev_log/2.1.348/crayon_202109271153.yaml
Labels: kind/bug, module/backend

#155 bugfix: 修复初次部署Django migrate报错：globalsettings doesn't exist (fixed #152)
  apps/node_man/apps.py
  dev_log/2.1.348/crayon_202109271203.yaml
Labels: kind/bug, module/saas

#164 bugfix: 修复插件列表前端403报错 (fixed #158)
  apps/node_man/handlers/permission.py
  dev_log/2.1.348/crayon_202109272121.yaml
Labels: kind/bug, module/saas

#169 bugfix: subscription/fetch_commands 接口报错 (fixed #159)
  apps/backend/agent/tools.py
  apps/backend/subscription/views.py
  dev_log/2.1.348/xcwang_20210927174853.yaml
Labels: kind/bug

#171 bugfix: Agent转安装Proxy报错问题(fixed #161)
  apps/backend/components/collections/agent.py
  apps/node_man/handlers/job.py
  apps/node_man/handlers/validator.py
  apps/node_man/models.py
  apps/node_man/tests/test_validator.py
  dev_log/2.1.348/durant_202109281505.yaml
Labels: kind/bug, module/saas
