Repository TencentBlueKing/bk-nodeman, pull requests merged in 2022-04, with the labels that each got.

#653 optimization: 安装 Proxy 时检查 GSE_BT_SERVER 的网络连通性 (close #612)
  apps/backend/components/collections/agent_new/check_policy_gse_to_proxy.py
  apps/backend/components/collections/job.py
  apps/backend/subscription/steps/agent.py
  apps/backend/tests/components/collections/agent_new/test_check_policy_gse_to_proxy.py
  apps/node_man/constants.py
  dev_log/2.2.10/durant_202204061710.yaml
  frontend/src/i18n/en.js
  frontend/src/i18n/zh.js
  frontend/src/views/cloud/cloud-manager-detail/cloud-detail-table.vue
  frontend/src/views/cloud/components/sideslider-content-edit.vue
  frontend/src/views/cloud/config/netTableConfig.ts
  frontend/src/views/cloud/config/proxy-detail-config.js
Labels: kind/optimization, module/backend, version/V2.2.X

#656 bugfix: 插件调试后残余debug进程的问题 (fixed #655)
  dev_log/2.2.10/durant_202204071142.yaml
  script_tools/plugin_scripts/stop_debug.ksh
  script_tools/plugin_scripts/stop_debug.sh
Labels: kind/bug, version/V2.2.X, module/script

#657 bugfix: 修复 Proxy 重载配置导致临时文件路径置空的问题 (closed #627)
  .pre-commit-config.yaml
  apps/backend/components/collections/agent_new/update_install_info.py
  dev_log/2.2.10/crayon_202204071611.yaml
Labels: kind/bug, module/backend, version/V2.2.X

#659 bugfix: 修复插件包停用后仍可被选中的问题 (closed #658)
  apps/backend/plugin/views.py
  apps/backend/subscription/steps/adapter.py
  dev_log/2.2.10/crayon_202204071956.yaml
Labels: kind/bug, module/backend, module/saas, version/V2.2.X

#662 bugfix: 修复插件部署策略编辑预览报错的问题 (closed #661)
  apps/backend/plugin/tools.py
  apps/backend/plugin/views.py
  apps/backend/subscription/steps/adapter.py
  dev_log/2.2.10/crayon_202204081939.yaml
Labels: kind/bug, module/backend, version/V2.2.X

#671 feature: 国际化 - 前端补充 (close #670)
  dev_log/2.2.10/daoqgong_202204131809.yaml
  frontend/src/i18n/en.js
  frontend/src/i18n/zh.js
Labels: kind/bug

#674 feature: 国际化 (closed #672)
  apps/backend/components/collections/agent_new/base.py
  apps/backend/components/collections/base.py
  apps/backend/components/collections/job.py
  apps/backend/periodic_tasks/check_zombie_sub_inst_record.py
  apps/backend/plugin/manager.py
  apps/backend/plugin/views.py
  apps/backend/subscription/handler.py
  apps/backend/subscription/steps/agent.py
  apps/backend/subscription/steps/base.py
  apps/backend/subscription/steps/plugin.py
  apps/backend/subscription/tasks.py
  apps/backend/subscription/views.py
  apps/node_man/handlers/meta.py
  apps/node_man/handlers/plugin.py
  apps/node_man/models.py
  apps/node_man/tools/policy.py
  apps/node_man/views/permission.py
  apps/utils/batch_request.py
  apps/utils/concurrent.py
  apps/utils/translation.py
  dev_log/2.2.10/crayon_202204132109.yaml
  frontend/src/i18n/en.js
  frontend/src/i18n/zh.js
  frontend/src/views/task/task-list-filter.vue
  locale/en/LC_MESSAGES/django.mo
  locale/en/LC_MESSAGES/django.po
Labels: kind/feature, version/V2.2.X

#676 bugfix: 修复 cookies 清除或过期后登录跳转异常的问题 (fixed #675)
  apps/node_man/handlers/iam.py
  apps/node_man/iam_provider.py
  apps/node_man/urls.py
  blueking/component/conf.py
  common/api/domains.py
  config/default.py
  dev_log/2.2.10/crayon_202204151728.yaml
  scripts/pack_ieod.sh
  static/remote/artdialog/jquery.artDialog.js
  static/remote/artdialog/skins/simple.css
Labels: kind/bug, module/saas, version/V2.2.X

#678 optimization: 插件配置实例查询优化 (closed #677)
  apps/node_man/migrations/0059_auto_20220415_2150.py
  apps/node_man/models.py
  dev_log/2.2.10/crayon_202204152153.yaml
Labels: module/backend, version/V2.2.X

#680 optimization: 修复下发服务模板采集报错：keyError 'service_template_id' 的问题 (fixed …
  apps/backend/subscription/tools.py
  dev_log/2.2.10/crayon_202204152204.yaml
Labels: kind/bug, module/backend, version/V2.2.X

#681 docs: 部署文档补充
  support-files/kubernetes/helm/bk-nodeman/README.md
  support-files/kubernetes/helm/bk-nodeman/templates/NOTES.txt
Labels: kind/bug, module/backend, version/V2.2.X

#684 bugfix: 修复多插件场景上下文渲染错误的问题 (fixed #683)
  apps/backend/agent/manager.py
  apps/backend/plugin/manager.py
  apps/backend/subscription/steps/agent.py
  apps/backend/subscription/steps/base.py
  apps/backend/subscription/steps/plugin.py
  dev_log/2.2.11/crayon_202204160150.yaml
Labels: kind/bug, version/V2.2.X

#686 feature: blueapps 升级至 4.2.3 (closed #685)
  dev_log/2.2.11/crayon_202204160202.yaml
  requirements.txt
Labels: version/V2.2.X, kind/dependencies

#698 feature: SaaS 相关任务创建接口返回任务链接 (closed #691)
  apps/node_man/handlers/job.py
  apps/node_man/handlers/plugin.py
  apps/node_man/handlers/plugin_v2.py
  apps/node_man/handlers/policy.py
  apps/node_man/tools/job.py
  apps/node_man/tools/policy.py
  dev_log/2.2.12/crayon_202204192139.yaml
  support-files/kubernetes/helm/bk-nodeman/README.md
  support-files/kubernetes/helm/bk-nodeman/templates/configmaps/env-configmap.yaml
Labels: kind/feature, module/saas, version/V2.2.X, module/docs

#702 bugfix: Helm ServiceMonitor 渲染错误 (fixed #701)
  apps/node_man/serializers/job.py
  dev_log/2.2.12/crayon_202204202237.yaml
  support-files/kubernetes/helm/bk-nodeman/templates/bklogconfig.yaml
  support-files/kubernetes/helm/bk-nodeman/templates/servicemonitor.yaml
  support-files/kubernetes/helm/bk-nodeman/values.yaml
Labels: kind/bug, version/V2.2.X

#703 feature: 同步业务主机接口 (closed #694)
  apps/node_man/handlers/permission.py
  apps/node_man/serializers/host.py
  apps/node_man/views/host.py
  dev_log/2.2.12/crayon_202204212213.yaml
Labels: kind/feature, module/saas, version/V2.2.X

#717 optimization: Agent 安装操作若主机存在于同业务下，视为重装 (closed #707)
  apps/backend/components/collections/agent_new/register_host.py
  apps/node_man/handlers/host.py
  apps/node_man/handlers/validator.py
  apps/node_man/tests/test_job.py
  dev_log/2.2.12/crayon_202204262243.yaml
Labels: kind/optimization, module/backend, module/saas, version/V2.2.X

#716 bugfix: init_official_plugins 命令支持第三方存储(close #708)
  apps/backend/management/commands/init_official_plugins.py
  apps/backend/tests/plugin/test_manage_commands.py
  apps/backend/tests/plugin/utils.py
  apps/backend/tests/plugin/views/test_plugin_production.py
  dev_log/2.2.12/xcwang_202204261913.yaml
Labels: kind/bug, module/backend, version/V2.2.X

#720 sprintfix: 修复第三方存储源导入插件包报错 && helm NOTES 添加插件包导入说明 (fixed #708)
  apps/backend/management/commands/init_official_plugins.py
  support-files/kubernetes/helm/bk-nodeman/README.md
  support-files/kubernetes/helm/bk-nodeman/templates/NOTES.txt
Labels: kind/bug, version/V2.2.X

#723 optimization: 统计订阅任务数据接口优化 (closed #695)
  apps/backend/subscription/handler.py
  apps/backend/subscription/serializers.py
  apps/backend/subscription/tools.py
  apps/backend/subscription/views.py
  apps/node_man/exceptions.py
  apps/utils/cache.py
  config/default.py
  dev_log/2.2.13/crayon_202204301746.yaml
Labels: kind/optimization, module/backend, version/V2.2.X
