Repository TencentBlueKing/bk-nodeman, pull requests merged in 2022-09, with the labels that each got.

#1034 optimization: 手动安装操作指引完善 (closed #722)
  dev_log/2.2.22/daoqgong_202209011700.yaml
  frontend/src/components/common/strategy-table.vue
  frontend/src/i18n/en.js
  frontend/src/i18n/zh.js
  frontend/src/types/task/task.ts
  frontend/src/views/task/task-detail-slider.vue
Labels: kind/optimization

#1032 feature: 产品导航新版设计 (close #882)
  dev_log/2.2.22/daoqgong_202209011618.yaml
  frontend/src/bk_icon_font/fonts/iconcool.eot
  frontend/src/bk_icon_font/fonts/iconcool.svg
  frontend/src/bk_icon_font/fonts/iconcool.ttf
  frontend/src/bk_icon_font/fonts/iconcool.woff
  frontend/src/bk_icon_font/style.css
  frontend/src/common/demand-import.ts
  frontend/src/common/util.ts
  frontend/src/components/common/nav-side.vue
  frontend/src/components/common/navigation.vue
  frontend/src/components/setup-table/table-header.vue
  frontend/src/css/app.css
  frontend/src/css/install-table.css
  frontend/src/i18n/en.js
  frontend/src/i18n/zh.js
  frontend/src/router/index.ts
  frontend/src/router/modules/agent-manager.ts
  frontend/src/router/modules/plugin-manager.ts
  frontend/src/router/modules/task-history-new.ts
  frontend/src/router/navigation-config.ts
  frontend/src/store/modules/main.ts
  frontend/src/views/agent/agent-list.vue
  frontend/src/views/plugin/plugin-list/plugin-list-operate.vue
  frontend/src/views/plugin/plugin-list/plugin-list.vue
  frontend/src/views/plugin/plugin-rule/plugin-rule-list/plugin-rule-operate.vue
  frontend/src/views/plugin/plugin-rule/plugin-rule-list/plugin-rule-table.vue
  frontend/src/views/plugin/plugin-rule/plugin-rule.vue
  frontend/src/views/plugin/resource-quota/index.vue
  frontend/src/views/plugin/resource-quota/resource-tree-item.vue
  frontend/src/views/task/task-detail-info.vue
  frontend/src/views/task/task-detail-new.vue
  frontend/src/views/task/task-list-filter.vue
  frontend/src/views/task/task-list.vue
Labels: kind/feature

#1039 bugfix: 插件模板序列化器错误 (closed #1037)
  apps/node_man/constants.py
  apps/node_man/migrations/0066_auto_20220906_1626.py
  apps/node_man/tests/test_constants.py
  dev_log/2.2.22/xcwang_202209061443.yaml
Labels: kind/bug, version/V2.2.X, priority/high

#1043 optimization: 补充 language 到 PaaSV2 部署配置 (closed #1042)
  app.yml
  dev_log/2.2.22/crayon_202209071725.yaml
Labels: kind/optimization, version/V2.2.X, priority/high

#1054 feature: 部署策略执行被抑制时，主抑制策略增加超链接 (closed #889)
  apps/backend/subscription/tasks.py
  apps/node_man/handlers/job.py
  dev_log/2.2.22/xcwang_202209071547.yaml
Labels: kind/optimization, module/saas, version/V2.2.X, priority/high

#1052 feature: 部署策略执行被抑制时，主抑制策略增加超链接 (closed #889)
  frontend/src/types/task/task.ts
  frontend/src/views/plugin/plugin-rule/plugin-rule-create/perform-preview.vue
  frontend/src/views/plugin/plugin-rule/plugin-rule.vue
  frontend/src/views/task/task-detail-table.vue
Labels: kind/feature

#1056 sprintfix: 修复抑制文案缺失的问题 (fixed #889)
  apps/backend/subscription/tasks.py
Labels: kind/bug, module/backend, version/V2.2.X

#1057 optimization: 插件操作执行预览补充当前插件版本 (closed #1049)
  apps/node_man/handlers/policy.py
  dev_log/2.2.22/crayon_202209101143.yaml
Labels: kind/optimization, module/saas, version/V2.2.X

#1058 sprintfix: 策略抑制跳转超链接 - 新打开窗口
  frontend/src/types/plugin/plugin-type.ts
  frontend/src/views/plugin/plugin-rule/plugin-rule-create/perform-preview.vue
  frontend/src/views/task/task-detail-table.vue
Labels: kind/optimization

#1061 feature: 完善权限中心「业务运维」权限配置，新增业务只读推荐权限 (closed #1060)
  apps/iam_migration/migrations/0006_bk_nodeman_202209111200.py
  dev_log/2.2.22/crayon_202209111303.yaml
  support-files/bkiam/0007_bk_nodeman_20210623-1512_iam.json
Labels: kind/feature, module/build, version/V2.2.X

#1062 feature: 重装 agent 时保存的密码如果仍在有效期内，需要回显成 *
  dev_log/2.2.22/daoqgong_202209130957.yaml
  frontend/src/common/form-check.ts
  frontend/src/components/setup-table/install-input-type.vue
  frontend/src/components/setup-table/install-table.vue
  frontend/src/config/config.ts
  frontend/src/views/agent/agent-setup/agent-import.vue
  frontend/src/views/agent/config/editTableConfig.ts
  frontend/src/views/cloud/components/sideslider-content-edit.vue
  frontend/src/views/cloud/components/sideslider-content.vue
Labels: kind/feature

#1065 optimization: 云区域支持全量排序 (closed #1046)
  dev_log/2.2.22/daoqgong202209131204.yaml
  frontend/src/views/cloud/cloud-manager.vue
Labels: kind/optimization

#1066 sprintfix: 非权限中心版本下云区域无展示问题修复
  frontend/src/views/cloud/cloud-manager.vue
Labels: kind/bug

#1067 sprintfix: 推荐权限国际化完善 (fixed #1060)
  apps/iam_migration/migrations/0007_bk_nodeman_202209131332.py
  support-files/bkiam/0007_bk_nodeman_20210623-1512_iam.json
Labels: kind/bug, module/frontend, version/V2.2.X

#1063 sprintfix: 插件状态标题及不刷新问题修复
  frontend/src/i18n/en.js
  frontend/src/i18n/zh.js
  frontend/src/router/modules/agent-manager.ts
  frontend/src/router/modules/plugin-manager.ts
  frontend/src/router/navigation-config.ts
  frontend/src/types/plugin/plugin-type.ts
  frontend/src/views/plugin/plugin-list/node-detail-slider.vue
  frontend/src/views/plugin/plugin-list/plugin-list-operate.vue
  frontend/src/views/plugin/plugin-list/plugin-list.vue
Labels: kind/bug

#1068 optimization: 插件任务版本提示优化 (closed #1048)
  dev_log/2.2.22/daoqgong_202209131833.yaml
  frontend/src/views/plugin/plugin-rule/plugin-rule-create/perform-preview.vue
  frontend/src/views/task/task-detail-new.vue
  frontend/src/views/task/task-detail-table.vue
Labels: kind/optimization

#1069 Bugfix/issue 911
  frontend/src/views/agent/components/parser-excel.vue
  static/download/bk_nodeman_info_en.xlsx
  static/download/bk_nodeman_info_en_address.xlsx
  static/download/bk_nodeman_info_zh.xlsx
  static/download/bk_nodeman_info_zh_address.xlsx
Labels: kind/bug

#1077 bugfix: 后台下载文件接口鉴权失败 (closed #1076)
  apps/backend/views.py
  dev_log/2.2.22/xcwang_202209151954.yaml
Labels: kind/bug, module/backend, version/V2.2.X

#1079 bugfix: Windows卸载命令拼接错误 (closed #1078)
  apps/backend/agent/solution_maker.py
  apps/backend/tests/components/collections/agent_new/test_install.py
  dev_log/2.2.23/xcwang_202209161638.yaml
Labels: kind/bug, module/backend, version/V2.2.X, priority/high

#1108 feature: 云区域列表增加可用 Proxy 数量信息 (#1083)
  apps/node_man/handlers/cloud.py
Labels: kind/feature, module/saas, version/V2.2.X

#1109 optimization: 安装 Agent 被忽略主机展示完整业务名称 (closed #1102)
  apps/node_man/handlers/validator.py
  dev_log/2.2.23/crayon_202209202041.yaml
Labels: kind/optimization, module/saas, version/V2.2.X

#1110 optimization: API 在线文档在生产环境隐藏 (closed #1107)
  dev_log/2.2.23/xcwang_202209201901.yaml
  urls.py
Labels: module/backend, version/V2.2.X, priority/high

#1112 optimization: 调整 Agent 卸载指引 (#1100 closed #1103)
  apps/backend/agent/solution_maker.py
  apps/node_man/constants.py
  apps/node_man/handlers/job.py
  dev_log/2.2.23/crayon_202209211111.yaml
Labels: kind/bug, kind/optimization, module/backend, module/saas, version/V2.2.X

#1113 optimization: 手动安装的安装说明需要完善 (closed #1082)
  dev_log/2.2.23/daoqgong_202209201434.yaml
  frontend/src/i18n/en.js
  frontend/src/i18n/zh.js
Labels: kind/optimization, module/frontend, version/V2.2.X, accepted

#1114 optimization: 插件停用时，应提供的是启用操作 (closed #1085)
  dev_log/2.2.23/daoqgong_202209201648.yaml
  frontend/src/views/plugin/plugin-package/plugin-package-table.vue
Labels: kind/optimization, module/frontend, version/V2.2.X, accepted

#1115 optimization: 资源配额 - 修改 执行文案改为下发配额 (closed #1089)
  dev_log/2.2.23/daoqgong_202209202053.yaml
  frontend/src/i18n/en.js
  frontend/src/i18n/zh.js
  frontend/src/views/plugin/resource-quota/edit.vue
Labels: kind/optimization, module/frontend, version/V2.2.X, accepted

#1116 optimization: 资源配额-配额百分比例含义不明确 (closed #1093)
  dev_log/2.2.23/daoqgong_202209202042.yaml
  frontend/src/i18n/en.js
  frontend/src/i18n/zh.js
  frontend/src/views/plugin/resource-quota/edit.vue
  frontend/src/views/plugin/resource-quota/index.vue
Labels: kind/optimization, module/frontend, version/V2.2.X, accepted

#1117 bugfix: 修复插件操作流水记录 Windows 服务器目录分隔符错误的问题 (fixed #1090)
  apps/backend/subscription/views.py
  dev_log/2.2.23/crayon_202209211156.yaml
Labels: kind/bug, module/backend, version/V2.2.X

#1118 optimization: 统一弹框话术 (closed #1084)
  dev_log/2.2.23/daoqgong_202209201614.yaml
  frontend/src/i18n/en.js
  frontend/src/i18n/zh.js
  frontend/src/views/cloud/cloud-manager-detail/cloud-detail-table.vue
Labels: kind/optimization, module/frontend, version/V2.2.X, accepted

#1119 optimization: 新建云区域界面 去掉 '选择' 二字 (closed #1097)
  dev_log/2.2.23/daoqgong_202209201718.yaml
  frontend/src/i18n/en.js
  frontend/src/i18n/zh.js
  frontend/src/views/cloud/cloud-manager-add/cloud-manager-add.vue
Labels: kind/optimization, module/frontend, version/V2.2.X, accepted

#1120 optimization: 插件包 表格列展示不全时提供tooltips (close #1086)
  dev_log/2.2.23/daoqgong_202209201710.yaml
  frontend/src/views/plugin/plugin-package/plugin-package-parsing.vue
  frontend/src/views/plugin/plugin-package/plugin-package-table.vue
Labels: kind/optimization, module/frontend, version/V2.2.X, accepted

#1122 bugfix: 编辑配额 - 编辑返回后，业务由全业务变成了单个业务 (closed #1088)
  dev_log/2.2.23/daoqgong_202209211558.yaml
  frontend/src/views/plugin/resource-quota/index.vue
Labels: accepted

#1123 bugfix: 手动卸载无指导方案问题 (closed #1100)
  dev_log/2.2.23/daoqgong_202209211632.yaml
  frontend/src/i18n/en.js
  frontend/src/i18n/zh.js
  frontend/src/views/task/task-detail-slider.vue
  frontend/src/views/task/task-detail-table.vue
  frontend/src/views/task/task-log.vue
Labels: kind/bug, kind/optimization, module/frontend, version/V2.2.X, accepted

#1125 optimization: 安装agent默认为已选择的单个业务 (closed #1095)
  dev_log/2.2.23/daoqgong_202209211452.yaml
  frontend/src/views/agent/agent-setup/agent-setup.vue
Labels: accepted

#1126 optimization: 部署策略 - 编辑类型button文案调整 (closed #1094)
  dev_log/2.2.23/daoqgong_202209211516.yaml
  frontend/src/i18n/en.js
  frontend/src/i18n/zh.js
  frontend/src/views/plugin/operateConfig.ts
  frontend/src/views/plugin/plugin-rule/plugin-rule-create/perform-preview.vue
Labels: accepted

#1127 feature: 云区域 - 调整列proxy数量为可用Proxy数量 (closed #1083)
  dev_log/2.2.23/daoqgong_202209211919.yaml
  frontend/src/i18n/en.js
  frontend/src/i18n/zh.js
  frontend/src/types/cloud/cloud.ts
  frontend/src/views/cloud/cloud-manager.vue
Labels: accepted

#1129 minor: add .ci
  .ci/codecc.yml
  urls.py
Labels: module/build, version/V2.2.X, kind/dependencies

#1131 sprintfix: 云区域nav列表去除异常状态，展示可用proxy提示
  frontend/src/views/cloud/cloud-manager-detail/cloud-detail-nav.vue
  frontend/src/views/cloud/cloud-manager-detail/cloud-manager-detail.vue
  frontend/src/views/cloud/cloud-manager.vue
  frontend/src/views/cloud/config/cloud-common.ts
  frontend/src/vue-proto.d.ts
Labels: accepted

#1130 bugfix: 表头图标被隐藏问题修复 （closed #1902 #1104)
  dev_log/2.2.24/daoqgong_202209221907.yaml
  frontend/src/setup/index.ts
  frontend/src/setup/text-tool.ts
  frontend/src/types/index.ts
  frontend/src/views/agent/agent-list.vue
  frontend/src/views/plugin/plugin-list/plugin-list-table.vue
  frontend/src/vue-proto.d.ts
Labels: accepted

#1133 optimization: 对 CMDB 编辑云区域后两边数据不一致的问题进行优化 (closed #1132)
  apps/node_man/constants.py
Labels: kind/optimization, module/saas, version/V2.2.X

#1134 optimization: 资源配额 - 规则及使用增加说明tips (closed #1087)
  dev_log/2.2.24/daoqgong_202209231119.yaml
  frontend/src/i18n/en.js
  frontend/src/i18n/zh.js
  frontend/src/views/plugin/resource-quota/index.vue
Labels: accepted

#1138 bugfix: 插件状态 - 过滤图标不展示问题修复 (closed #1137)
  dev_log/2.2.25/daoqgong_202209231640.yaml
  frontend/src/views/plugin/plugin-list/plugin-list-table.vue
Labels: kind/bug

#1141 optimization: 复制IP默认以换行符进行分隔 (closed #1140)
  dev_log/2.2.26/daoqgong_202209261602.yaml
  frontend/package-lock.json
  frontend/package.json
  frontend/src/common/util.ts
  frontend/src/i18n/en.js
  frontend/src/i18n/zh.js
  frontend/src/setup/directives.ts
  frontend/src/vue-proto.d.ts
Labels: kind/optimization, accepted

#1142 sprintfix: 统一弹框话术
  frontend/src/components/common/navigation.vue
  frontend/src/i18n/en.js
  frontend/src/i18n/zh.js
Labels: accepted

#1145 minor: pyOpenSSL 版本固化 21.0.0 (closed #1144)
  dev_log/2.2.26/crayon_202209261741.yaml
  requirements.txt
Labels: kind/optimization, version/V2.2.X, kind/dependencies

#1147 minor: 移除冗余代码
  apps/backend/agent/tools.py
Labels: module/backend, version/V2.2.X

#1148 optimization: 国际化处理 (closed #1146)
  dev_log/2.2.27/daoqgong_202209271735.yaml
  frontend/src/components/common/nav-side.vue
  frontend/src/components/setup-table/table-header.vue
  frontend/src/i18n/en.js
  frontend/src/i18n/zh.js
  frontend/src/setup/i18n-setup.ts
Labels: kind/optimization, accepted
