Repository TencentBlueKing/bk-nodeman, pull requests merged in 2022-02, with the labels that each got.

#477 optimization: 提升通过 SSH 通道批量安装 Agent 的稳定性和效率 (closed #463)
  apps/backend/agent/tools.py
  apps/backend/components/collections/agent_new/base.py
  apps/backend/components/collections/agent_new/choose_access_point.py
  apps/backend/components/collections/agent_new/install.py
  apps/backend/components/collections/base.py
  apps/backend/components/collections/core.py
  apps/backend/constants.py
  apps/backend/tests/components/collections/agent_new/test_choose_access_point.py
  apps/backend/tests/components/collections/agent_new/test_install.py
  apps/backend/tests/components/collections/agent_new/utils.py
  apps/backend/tests/view/base.py
  apps/backend/tests/view/test_get_gse_config.py
  apps/backend/tests/view/test_report_log.py
  apps/backend/views.py
  apps/core/concurrent/lock.py
  apps/core/remote/__init__.py
  apps/core/remote/benchmark/__init__.py
  apps/core/remote/benchmark/conns/__init__.py
  apps/core/remote/benchmark/conns/core.py
  apps/core/remote/conns/__init__.py
  apps/core/remote/conns/asyncssh_impl.py
  apps/core/remote/conns/base.py
  apps/core/remote/conns/paramiko_impl.py
  apps/core/remote/constants.py
  apps/core/remote/exceptions.py
  apps/core/remote/tests/__init__.py
  apps/core/remote/tests/base.py
  apps/core/remote/tests/test_conns.py
  apps/node_man/models.py
  apps/utils/concurrent.py
  apps/utils/exc.py
  config/default.py
  dev_log/2.2.1/crayon_202202151209.yaml
  ignorefile
  requirements.txt
Labels: kind/optimization, module/backend

#484 feature: 资源配额前端开发 (closed #421)
  frontend/src/bk_icon_font/fonts/iconcool.eot
  frontend/src/bk_icon_font/fonts/iconcool.svg
  frontend/src/bk_icon_font/fonts/iconcool.ttf
  frontend/src/bk_icon_font/fonts/iconcool.woff
  frontend/src/bk_icon_font/style.css
  frontend/src/common/form-check.ts
  frontend/src/css/app.css
  frontend/src/i18n/zh.js
  frontend/src/main.ts
  frontend/src/router/modules/plugin-manager.ts
  frontend/src/router/navigation-config.ts
  frontend/src/store/modules/plugin-new.ts
  frontend/src/views/plugin/resource-quota/edit.vue
  frontend/src/views/plugin/resource-quota/index.vue
  frontend/src/views/plugin/resource-quota/resource-tree-item.vue
  frontend/src/views/plugin/resource-quota/resource-tree.vue
Labels: kind/feature

#486 feature: 资源配额前端开发 (closed #421)
  frontend/src/bk_icon_font/fonts/iconcool.eot
  frontend/src/bk_icon_font/fonts/iconcool.svg
  frontend/src/bk_icon_font/fonts/iconcool.ttf
  frontend/src/bk_icon_font/fonts/iconcool.woff
  frontend/src/bk_icon_font/style.css
  frontend/src/common/form-check.ts
  frontend/src/css/app.css
  frontend/src/i18n/zh.js
  frontend/src/main.ts
  frontend/src/router/modules/plugin-manager.ts
  frontend/src/router/navigation-config.ts
  frontend/src/store/modules/plugin-new.ts
  frontend/src/views/plugin/resource-quota/edit.vue
  frontend/src/views/plugin/resource-quota/index.vue
  frontend/src/views/plugin/resource-quota/resource-tree-item.vue
  frontend/src/views/plugin/resource-quota/resource-tree.vue
Labels: kind/feature

#480 feature: 资源配额功能(close #478)
  apps/backend/components/collections/plugin.py
  apps/backend/subscription/tools.py
  apps/backend/tests/components/collections/plugin/test_gse_operate_proc.py
  apps/backend/tests/components/collections/plugin/utils.py
  apps/mock_data/api_mkd/cmdb/utils.py
  apps/node_man/constants.py
  apps/node_man/exceptions.py
  apps/node_man/handlers/cmdb.py
  apps/node_man/handlers/plugin_v2.py
  apps/node_man/migrations/0056_pluginresourcepolicy.py
  apps/node_man/models.py
  apps/node_man/serializers/cmdb.py
  apps/node_man/serializers/plugin_v2.py
  apps/node_man/tests/test_pluginv2.py
  apps/node_man/tests/utils.py
  apps/node_man/views/cmdb.py
  apps/node_man/views/plugin_v2.py
  apps/utils/generate_api_js.py
  blueking/component/apis/cc.py
  common/context_processors.py
  dev_log/2.2.1/durant_202202151743.yaml
  frontend/index.html
  frontend/src/api/modules/cmdb.js
  frontend/src/api/modules/plugin_v2.js
  frontend/static/lib-manifest.json
  frontend/static/lib.bundle.js
  frontend/static/lib.bundle.js.LICENSE.txt
  static/apidoc/index.html
  static/index.html
Labels: kind/feature, version/V2.2.X

#474 feature: ZK账号加密支持多操作系统工具区分
  apps/backend/utils/encrypted.py
  dev_log/2.2.1/xcwang_202201181726.yaml
  script_tools/encryptedpasswd/linux_aarch64/encryptedpasswd
  script_tools/encryptedpasswd/linux_x86_64/encryptedpasswd
Labels: module/backend

#492 bugfix: 版本日志路由错误问题 (fixed #489)
  apps/node_man/tests/test_views.py
  apps/node_man/urls.py
  dev_log/2.2.1/durant_202202221052.yaml
Labels: kind/bug, module/saas, version/V2.2.X

#495 feature: 作业平台调用支持业务集 (closed #493)
  apps/backend/api/job.py
  apps/backend/components/collections/job.py
  apps/backend/components/collections/plugin.py
  apps/mock_data/api_mkd/job/unit.py
  apps/node_man/constants.py
  apps/node_man/periodic_tasks/update_proxy_file.py
  apps/node_man/periodic_tasks/utils.py
  dev_log/2.2.1/durant_202202221200.yaml
Labels: kind/feature, module/backend, version/V2.2.X

#497 bugfix: 手动安装命令错误(fixed issue#496)
  apps/node_man/handlers/job.py
  apps/node_man/serializers/job.py
  apps/node_man/tests/test_job.py
  dev_log/2.2.1/durant_202202221745.yaml
Labels: kind/bug, module/saas, version/V2.2.X

#505 feature: 云区域接入点修改时支持预览 (closed #502)
  dev_log/2.1.366/daoqgong_202202241438.yaml
  frontend/src/components/common/tips.vue
  frontend/src/i18n/en.js
  frontend/src/i18n/zh.js
  frontend/src/router/modules/cloud-manager.ts
  frontend/src/views/cloud/cloud-manager-add/cloud-manager-add.vue
  frontend/src/views/cloud/cloud-manager-add/cloud-manager-preview.vue
  frontend/src/views/cloud/cloud-manager-detail/cloud-detail-table.vue
Labels: kind/feature

#506 feature: Windows 直连安装 Agent 支持 Cygwin (closed #475)
  apps/backend/agent/tools.py
  apps/backend/components/collections/agent_new/choose_access_point.py
  apps/backend/components/collections/agent_new/install.py
  apps/backend/components/collections/common/remote.py
  apps/backend/tests/components/collections/agent_new/test_choose_access_point.py
  apps/backend/tests/components/collections/agent_new/test_install.py
  apps/backend/tests/components/collections/agent_new/utils.py
  apps/core/remote/__init__.py
  apps/core/remote/clients/file.py
  apps/core/remote/conns/asyncssh_impl.py
  apps/core/remote/conns/base.py
  apps/core/remote/conns/paramiko_impl.py
  apps/core/remote/exceptions.py
  apps/core/remote/tests/base.py
  apps/mock_data/common_unit/host.py
  apps/utils/basic.py
  dev_log/2.2.1/crayon_202202242056.yaml
Labels: kind/feature
