Repository TencentBlueKing/bk-nodeman, pull requests merged in 2022-07, with the labels that each got.

#904 optimization: 登录跳转取消弹框 (close #843)
  config/default.py
  dev_log/2.2.18/crayon_202206301737.yaml
Labels: kind/optimization, module/saas, version/V2.2.X

#921 optimization: 添加主机到 CMDB 兼容接口数据延迟的情况 (close #920)
  apps/backend/components/collections/agent_new/register_host.py
  apps/backend/tests/components/collections/agent_new/test_register_host.py
  dev_log/2.2.18/crayon_202207071036.yaml
Labels: kind/optimization, module/backend, version/V2.2.X, priority/high

#829 feature: 支持 AIX 操作系统区分版本 (closed #815)
  apps/backend/components/collections/agent_new/base.py
  apps/backend/components/collections/agent_new/install.py
  apps/backend/exceptions.py
  apps/backend/tests/components/collections/agent_new/test_install.py
  apps/backend/tests/components/collections/agent_new/test_push_upgrade_package.py
  apps/node_man/constants.py
  apps/node_man/handlers/meta.py
  apps/node_man/migrations/0023_init_proxy_package.py
  apps/node_man/migrations/0060_host_os_version.py
  apps/node_man/models.py
  dev_log/2.2.19/xcwang_202206091632.yaml
  script_tools/setup_agent.ksh
  script_tools/upgrade_agent.sh.tpl
Labels: kind/feature, module/backend, module/saas, version/V2.2.X

#939 feature: Nginx 重新编译，修复 DNS 漏洞 (closed #918)
  dev_log/2.2.19/xcwang_202207192113.yaml
  script_tools/nginx-portable.tgz
  support-files/images/nginx/Dockerfile
  support-files/images/nginx/README.md
Labels: kind/feature, module/build, version/V2.2.X, module/script

#942 optimization: IPv6 校验及展示优化 (closed #942)
  apps/adapters/api/gse/v1.py
  apps/backend/components/collections/agent_new/add_or_update_hosts.py
  apps/backend/components/collections/agent_new/get_agent_status.py
  apps/backend/subscription/steps/plugin.py
  apps/backend/subscription/tasks.py
  apps/backend/tests/components/collections/agent_new/test_configure_policy.py
  apps/backend/tests/components/collections/agent_new/test_install.py
  apps/backend/tests/components/collections/agent_new/utils.py
  apps/node_man/handlers/cloud.py
  apps/node_man/handlers/host.py
  apps/node_man/handlers/job.py
  apps/node_man/handlers/validator.py
  apps/node_man/models.py
  apps/node_man/periodic_tasks/sync_agent_status_task.py
  apps/node_man/periodic_tasks/sync_proc_status_task.py
  apps/node_man/tests/test_handlers/test_host.py
  apps/node_man/tests/utils.py
  apps/node_man/tools/host_v2.py
  apps/utils/basic.py
  dev_log/2.2.19/crayon_202207211225.yaml
Labels: kind/optimization, module/backend, module/saas, version/V2.2.X

#944 feature: 产品 logo 增加加跳转至首页的超链 (closed #915)
  dev_log/2.2.19/daoqing_202207111820.yaml
  frontend/src/components/common/navigation.vue
Labels: kind/feature, kind/optimization

#945 bugfix: Agent 安装校验提示信息错位 (closed #669)
  dev_log/2.2.19/daoqing_202207110923.yaml
  frontend/src/components/common/verify-input.vue
Labels: kind/bug

#946 feature: Agent 导入表头支持云区域搜索 (closed #913)
  dev_log/2.2.19/daoqgong202207111755.yaml
  frontend/src/components/setup-table/input-type.vue
  frontend/src/components/setup-table/install-table.vue
  frontend/src/components/setup-table/table-header.vue
  frontend/src/views/agent/config/importTableConfig.js
Labels: kind/feature, kind/optimization

#947 feature: 历史任务-执行日志整体重试改为重试 (closed #899)
  dev_log/2.2.19/daoqing_202207111720.yaml
  frontend/src/views/task/task-log.vue
Labels: kind/feature, kind/optimization

#948 feature: 云区域排序规则 (closed #897)
  dev_log/2.2.19/daoqing_202207111708.yaml
  frontend/src/views/cloud/cloud-manager.vue
Labels: kind/feature, kind/optimization

#950 feature: 支持多个node版本开发、打包 (closed #938)
  dev_log/2.2.19/daoqgong_202207191822.yaml
  frontend/package.json
  frontend/src/components/common/right-panel.vue
  frontend/src/components/common/verify-input.vue
  frontend/src/components/ip-selector/business/topo-selector-nodeman.vue
  frontend/src/components/ip-selector/components/ip-selector-table.vue
  frontend/src/components/ip-selector/components/selection-column.vue
  frontend/src/components/ip-selector/components/topo-tree.vue
  frontend/src/components/ip-selector/layout/custom-input.vue
  frontend/src/components/ip-selector/selector/selector-preview.vue
  frontend/src/views/global-config/gse-config/index.vue
  frontend/src/views/global-config/gse-config/set-access-point/step-host.vue
  frontend/src/views/global-config/gse-config/set-access-point/step-info.vue
  frontend/src/views/global-config/task-config.vue
  frontend/src/views/plugin/plugin-rule/plugin-rule-create/perform-preview.vue
  frontend/src/views/plugin/resource-quota/edit.vue
  frontend/src/views/plugin/resource-quota/resource-tree-item.vue
  frontend/src/views/task/task-detail-slider.vue
  frontend/src/views/task/task-detail-table.vue
  frontend/src/views/task/task-detail.vue
  frontend/src/views/task/task-log.vue
Labels: kind/optimization, kind/dependencies

#951 feature: 支持主机名展示及过滤 (closed #936)
  apps/backend/subscription/tools.py
  apps/node_man/handlers/host.py
  apps/node_man/handlers/host_v2.py
  apps/node_man/handlers/meta.py
  apps/node_man/handlers/plugin.py
  apps/node_man/migrations/0064_auto_20220721_1557.py
  apps/node_man/models.py
  apps/node_man/periodic_tasks/sync_cmdb_host.py
  apps/node_man/tests/test_handlers/test_meta.py
  dev_log/2.2.19/crayon_202207211716.yaml
Labels: kind/feature, module/backend, module/saas, version/V2.2.X

#956 optimization: GSE 配置文件去掉相关注释，保证json格式合法 (closed #955)
  apps/backend/readme.md
  apps/backend/views.py
  dev_log/2.2.19/xcwang_202207251642.yaml
Labels: kind/optimization, module/backend, version/V2.2.X

#954 docs: 开源信息更新 (closed #953)
  dev_log/2.2.19/xcwang_202207251142.yaml
  readme.md
  readme_en.md
Labels: version/V2.2.X, module/docs

#960 bugfix: 节点列表表头展示问题修复
  frontend/src/views/agent/agent-list.vue
  frontend/src/views/plugin/plugin-list/plugin-list-table.vue
  frontend/src/views/plugin/plugin-list/plugin-list.vue
Labels: kind/bug

#964 feature: 产品页面支持 IPV6 主机导入 (closed #776)
  dev_log/2.2.19/daoqgong_202207281500.yaml
  frontend/src/common/form-check.ts
  frontend/src/components/common/column-setting.vue
  frontend/src/config/config.ts
  frontend/src/i18n/en.js
  frontend/src/i18n/zh.js
  frontend/src/router/index.ts
  frontend/src/types/agent/agent-type.ts
  frontend/src/types/cloud/cloud.ts
  frontend/src/types/index.ts
  frontend/src/types/plugin/plugin-type.ts
  frontend/src/types/task/task.ts
  frontend/src/views/agent/agent-list.vue
  frontend/src/views/agent/agent-setup/agent-import.vue
  frontend/src/views/agent/agent-setup/agent-setup.vue
  frontend/src/views/agent/components/parser-excel.vue
  frontend/src/views/agent/config/editTableConfig.ts
  frontend/src/views/agent/config/importTableConfig.js
  frontend/src/views/agent/config/setupTableConfig.ts
  frontend/src/views/cloud/cloud-manager-add/cloud-manager-setup.vue
  frontend/src/views/cloud/components/sideslider-content.vue
  frontend/src/views/cloud/config/netTableConfig.ts
  frontend/src/views/plugin/plugin-list/plugin-list-table.vue
  frontend/src/views/plugin/plugin-list/plugin-list.vue
  frontend/src/views/task/task-detail-new.vue
  frontend/src/views/task/task-detail-slider.vue
  frontend/src/views/task/task-detail-table.vue
  frontend/src/views/task/task-log.vue
  static/download/bk_nodeman_info_en.xlsx
  static/download/bk_nodeman_info_zh.xlsx
Labels: kind/feature, module/frontend, version/V2.2.X

#969 bugfix: 打包时少量css报错问题 (closed #968)
  frontend/src/components/ip-selector/business/topo-selector-nodeman.vue
  frontend/src/components/ip-selector/components/ip-selector-table.vue
  frontend/src/components/ip-selector/components/selection-column.vue
  frontend/src/components/ip-selector/components/topo-tree.vue
  frontend/src/components/ip-selector/layout/custom-input.vue
  frontend/src/components/ip-selector/selector/selector-preview.vue
  frontend/src/components/ip-selector/selector/selector-tab.vue
  frontend/src/store/index.ts
Labels: kind/bug

#971 feature: IPv4/IPv6 双栈 k8s 部署适配 (closed #970)
  bin/hooks/start-saas-api
  bin/hooks/start_cmds/start-backend-api
  dev_log/2.2.19/crayon_202207291955.yaml
  support-files/kubernetes/helm/bk-nodeman/templates/configmaps/saas-web-nginx-configmap.yaml
  support-files/kubernetes/helm/bk-nodeman/templates/migrate-jobs/db-migrate-job.yaml
  support-files/kubernetes/helm/bk-nodeman/templates/migrate-jobs/file-sync-migrate-job.yaml
Labels: kind/feature, module/build, version/V2.2.X
