Repository TencentBlueKing/bk-nodeman, pull requests merged in 2022-08, with the labels that each got.

#974 bugfix: Linux Agent dbgipc 配置渲染值有误 (fixed #973)
  apps/backend/views.py
  dev_log/2.2.19/crayon_202208011750.yaml
Labels: kind/bug, module/backend, version/V2.2.X, priority/high

#979 bugfix: 修复tip操作hover、click冲突问题，优化端口批量操作
  frontend/src/components/setup-table/install-table.vue
  frontend/src/components/setup-table/table-header-tip.vue
  frontend/src/components/setup-table/table-header.vue
  frontend/src/config/config.ts
  frontend/src/i18n/en.js
  frontend/src/i18n/zh.js
  frontend/src/store/modules/main.ts
Labels: kind/bug

#989 bugfix: AIX 适配升级脚本语法错误 (closed #987)
  dev_log/2.2.20/xcwang_202208091453.yaml
  script_tools/upgrade_agent.sh.tpl
Labels: kind/bug, module/backend, version/V2.2.X

#983 bugfix: JOB API适配接口错误
  apps/backend/components/collections/job.py
  apps/backend/components/collections/plugin.py
  apps/backend/tests/components/collections/agent_new/test_check_policy_gse_to_proxy.py
  dev_log/2.2.20/xcwang_202208091707.yaml
Labels: kind/bug, module/backend, version/V2.2.X

#992 feature: 未启用 DHCP 适配时前端关闭部分入口 (closed #978)
  dev_log/2.2.20/daoqgong_202208100948.yaml
  frontend/src/config/config.ts
  frontend/src/views/agent/agent-list.vue
  frontend/src/views/plugin/plugin-list/plugin-list-table.vue
Labels: kind/feature

#991 feature: Agent 安装表单优化 (closed #869)
  dev_log/2.2.20/daoqgong_202208100939.yaml
  frontend/index-dev.html
  frontend/src/components/setup-table/install-input-type.vue
  frontend/src/components/setup-table/install-table.vue
  frontend/src/components/setup-table/table-header-tip.vue
  frontend/src/components/setup-table/table-header.vue
  frontend/src/config/config.ts
  frontend/src/css/app.css
  frontend/src/css/install-table.css
  frontend/src/i18n/en.js
  frontend/src/i18n/zh.js
  frontend/src/store/modules/main.ts
  frontend/src/types/index.ts
  frontend/src/views/agent/agent-setup/agent-import.vue
  frontend/src/views/agent/agent-setup/agent-setup.vue
  frontend/src/views/agent/config/editTableConfig.ts
  frontend/src/views/agent/config/importTableConfig.js
  frontend/src/views/agent/config/setupTableConfig.ts
  frontend/src/views/cloud/config/netTableConfig.ts
Labels: kind/feature

#996 bugfix: 修复插件调试接口报错的问题 (fixed #995)
  apps/backend/plugin/serializers.py
  apps/backend/plugin/views.py
  dev_log/2.2.21/crayon_202208120947.yaml
Labels: kind/bug, module/backend, version/V2.2.X, priority/high

#999 sprintfix: 修复获取调试任务状态报错的问题
  apps/backend/components/collections/plugin.py
Labels: kind/bug, module/backend, version/V2.2.X

#965 optimization: 安装命令生成执行方案，Windows 非直连安装 Agent 支持 Cygwin (close #740)
  apps/backend/agent/solution_maker.py
  apps/backend/agent/tools.py
  apps/backend/components/collections/agent_new/install.py
  apps/backend/subscription/views.py
  apps/backend/tests/components/collections/agent_new/test_install.py
  apps/node_man/constants.py
  apps/utils/basic.py
  dev_log/2.2.22/crayon_202208150954.yaml
  frontend/src/views/agent/config/editTableConfig.ts
  frontend/src/views/agent/config/importTableConfig.js
  script_tools/setup_pagent.py
Labels: module/backend, version/V2.2.X, module/script

#1001 feature: SaaS 支持 JWT 校验 (closed #1000)
  config/default.py
Labels: kind/bug, module/saas, version/V2.2.X

#1009 bugfix: 修复判断主机能否使用第三方查询密码服务不可用的问题 (fixed #1008)
  apps/node_man/views/password.py
  dev_log/2.2.22/crayon_202208172039.yaml
Labels: kind/bug, module/saas, version/V2.2.X, priority/high

#1012 feature: 订阅更新接口支持 steps 更新 (closed #1002)
  apps/backend/subscription/errors.py
  apps/backend/subscription/serializers.py
  apps/backend/subscription/views.py
  apps/node_man/migrations/0065_alter_subscriptionstep_unique_together.py
  apps/node_man/models.py
  dev_log/2.2.22/crayon_202208191706.yaml
Labels: module/backend, version/V2.2.X, priority/high

#990 optimization: Agent 安装脚本移除启动插件逻辑 (closed #727)
  dev_log/2.2.20/xcwang_202208091907.yaml
  script_tools/setup_agent.sh
  script_tools/setup_agent.zsh
  script_tools/setup_proxy.sh
  script_tools/setup_solaris_agent.sh
Labels: kind/optimization, module/backend, version/V2.2.X

#1014 feature: Agent 安装前置创建目录 (closed #977)
  apps/backend/agent/solution_maker.py
  apps/backend/tests/components/collections/agent_new/test_install.py
  dev_log/2.2.22/crayon_202208221655.yaml
  script_tools/setup_pagent.py
Labels: kind/feature, module/backend, version/V2.2.X, module/script

#1015 bugfix: 自定义业务拓扑场景下新建策略报错 (closed #1010)
  apps/iam/handlers/resources.py
  apps/node_man/tools/host_v2.py
  dev_log/2.2.22/xcwang_202208221738.yaml
Labels: kind/bug, module/backend, version/V2.2.X

#1022 optimization: 插件订阅变更计算移除冗余配置实例生成逻辑 (closed #1003)
  apps/backend/subscription/steps/adapter.py
  apps/backend/subscription/steps/plugin.py
  dev_log/2.2.22/crayon_202208261637.yaml
Labels: kind/optimization, module/backend, version/V2.2.X

#1026 feature: 增加埋点，Trace 接入 (#603)
  apps/__init__.py
  apps/backend/subscription/views.py
  apps/node_man/apps.py
  apps/node_man/handlers/plugin.py
  apps/node_man/models.py
  apps/prometheus/middlewares.py
  apps/prometheus/models.py
  config/default.py
  dev_log/2.2.22/crayon_202208302023.yaml
  env/__init__.py
  requirements.txt
  support-files/kubernetes/helm/bk-nodeman/README.md
  support-files/kubernetes/helm/bk-nodeman/templates/configmaps/backend-env-configmap.yaml
  support-files/kubernetes/helm/bk-nodeman/templates/configmaps/env-configmap.yaml
  support-files/kubernetes/helm/bk-nodeman/values.yaml
Labels: kind/optimization, module/backend, version/V2.2.X

#1025 optimization: helm charts matchLabels 补充 (closed #1024)
  dev_log/2.2.22/crayon_202208301930.yaml
  support-files/kubernetes/helm/bk-nodeman/templates/backend-api/deployment.yaml
  support-files/kubernetes/helm/bk-nodeman/templates/backend-celery/baworker-deployment.yaml
  support-files/kubernetes/helm/bk-nodeman/templates/backend-celery/bworker-deployment.yaml
  support-files/kubernetes/helm/bk-nodeman/templates/backend-celery/celery-beat-deployment.yaml
  support-files/kubernetes/helm/bk-nodeman/templates/backend-celery/common-pworker-deployment.yaml
  support-files/kubernetes/helm/bk-nodeman/templates/backend-celery/common-worker-deployment.yaml
  support-files/kubernetes/helm/bk-nodeman/templates/backend-celery/dworker-deployment.yaml
  support-files/kubernetes/helm/bk-nodeman/templates/backend-celery/paworker-deployment.yaml
  support-files/kubernetes/helm/bk-nodeman/templates/backend-celery/psworker-deployment.yaml
  support-files/kubernetes/helm/bk-nodeman/templates/backend-celery/pworker-deployment.yaml
  support-files/kubernetes/helm/bk-nodeman/templates/saas-api/deployment.yaml
  support-files/kubernetes/helm/bk-nodeman/templates/web/deployment.yaml
Labels: kind/optimization, module/build, version/V2.2.X

#1027 sprintfix: 命名规范 BKAPP_OTEL_GRPC_HOST -> BKAPP_OTEL_GRPC_URL (#603)
  config/default.py
  env/__init__.py
  support-files/kubernetes/helm/bk-nodeman/README.md
  support-files/kubernetes/helm/bk-nodeman/templates/configmaps/env-configmap.yaml
  support-files/kubernetes/helm/bk-nodeman/values.yaml
Labels: kind/bug, module/backend, module/build, version/V2.2.X
