Repository TencentBlueKing/bk-nodeman, pull requests merged in 2022-01, with the labels that each got.

#409 feature: 异步接口超时复制IP失败优化 (closed #404）
  dev_log/2.1.364/daoqgong_202112291813.yaml
  frontend/package.json
  frontend/src/common/util.ts
  frontend/src/components/common/strategy-table.vue
  frontend/src/components/ip-select-nm/node-preview.vue
  frontend/src/views/agent/agent-list.vue
  frontend/src/views/cloud/cloud-manager-detail/cloud-detail-table.vue
  frontend/src/views/cloud/cloud-manager.vue
  frontend/src/views/plugin/plugin-list/plugin-list-operate.vue
  frontend/src/views/plugin/plugin-rule/plugin-rule-create/variable-popover.vue
  frontend/src/views/task/task-detail-new.vue
  frontend/src/views/task/task-detail-slider.vue
  frontend/src/views/task/task-detail.vue
Labels: kind/optimization

#423 bugfix: 修复 PyNaCl 依赖安装报错的问题
  dev_log/2.1.364/crayon_202201111208.yaml
  requirements.txt
Labels: kind/bug, version/V2.1.X, module/framework

#408 feature: Agent 管理页面支持在 url 中进行条件过滤 (closed #405)
  dev_log/2.1.364/daoqgong_202112311419.yaml
  frontend/src/router/modules/agent-manager.ts
  frontend/src/views/agent/agent-list.vue
Labels: kind/feature

#424 optimization: 安装脚本优化(close #415)
  dev_log/2.1.364/durant_202201111531.yaml
  script_tools/setup_agent.sh
Labels: kind/optimization, version/V2.1.X_dev, module/script

#426 sprintfix: 修复更新安装信息Service不匹配的问题
  apps/backend/agent/manager.py
Labels: kind/bug, version/V2.2.X

#429 bugfix: redis sentinel 连接死循环(fixed #427)
  dev_log/2.1.365/durant_202201111531.yaml
  requirements.txt
Labels: kind/bug

#443 sprintfix: 修复 Agent 安装过程托管插件步骤因不支持相应操作系统失败的问题 (closed #442)
  apps/backend/components/collections/agent_new/delegate_plugin_proc.py
  apps/backend/tests/components/collections/agent_new/test_delegate_plugin_proc.py
Labels: kind/bug, module/backend, version/V2.2.X

#439 feature: 插件操作入口优化(closed #434)
  dev_log/2.1.365/daoqgong_202201151729.yaml
  frontend/src/i18n/en.js
  frontend/src/i18n/zh.js
  frontend/src/views/plugin/plugin-list/plugin-list.vue
Labels: kind/feature, kind/optimization

#438 feature: 去掉 agent、proxy 的「移除」入口(closed #436)
  dev_log/2.1.365/daoqgong_202201151736.yaml
  frontend/src/views/agent/agent-list.vue
  frontend/src/views/cloud/cloud-manager-detail/cloud-detail-table.vue
Labels: kind/feature

#445 sprintfix: 停止插件进程失败 type object 'GseDataErrCode' has no attribute 'NO…
  apps/backend/components/collections/plugin.py
Labels: kind/bug, module/backend, version/V2.2.X

#453 bugfix: 修复 Agent 安装过程托管插件步骤因不支持相应操作系统失败的问题 (closed #442)
  apps/backend/components/collections/agent_new/delegate_plugin_proc.py
  apps/backend/tests/components/collections/agent_new/test_delegate_plugin_proc.py
  apps/node_man/tests/test_views.py
Labels: kind/bug, module/backend, version/V2.2.X

#455 optimization: 并发控制参数优化
  apps/backend/components/collections/agent_new/choose_access_point.py
  apps/backend/components/collections/agent_new/install.py
  apps/backend/components/collections/core.py
  apps/backend/tests/components/collections/agent_new/test_choose_access_point.py
Labels: kind/optimization, module/backend, version/V2.2.X

#462 optimization: 优化windows安装脚本执行慢的问题(close #461)
  script_tools/setup_agent.bat
Labels: kind/optimization, version/V2.2.X, module/script

#460 feature: 铁将军密码库接入 (closed #459)
  apps/backend/components/collections/agent_new/query_password.py
  apps/backend/tests/components/collections/agent_new/test_query_password.py
  apps/node_man/handlers/password.py
  apps/node_man/tests/test_tjj.py
  apps/node_man/views/password.py
  dev_log/2.2.1/crayon_202201211030.yaml
Labels: kind/feature, module/backend, version/V2.2.X, pr/deferred(暂不合入)

#467 bugfix: 修复windows目标机器路径拼接错误的问题 (close #466)
  apps/utils/files.py
  apps/utils/tests/test_files.py
Labels: kind/bug, module/backend, version/V2.2.X
