Repository TencentBlueKing/bk-nodeman, pull requests merged in 2022-11, with the labels that each got.

#1203 bugfix: 2.0 Agent 配置文件更新流程错误 (closed #1202)
  dev_log/2.2.31/xcwang_202210311057.yaml
  script_tools/agent_tools/agent2/setup_agent.sh
  script_tools/agent_tools/agent2/setup_proxy.sh
Labels: module/backend, module/script

#1207 bugfix: 修复临时文件目录不同导致下发路径不符合预期的问题 (fixed #1204)
  apps/backend/components/collections/plugin.py
  dev_log/2.2.31/crayon_202210312315.yaml
Labels: kind/bug, module/backend, version/V2.2.X

#1216 bugfix: ZK 加密工具多操作系统路径判断错误 (closed #1214)
  apps/backend/utils/encrypted.py
  dev_log/2.2.32/xcwang_202211021547.yaml
Labels: module/backend, version/V2.2.X

#1212 feature: 新版 IP 选择器接入 (closed #1211)
  dev_log/2.2.32/daoqgong_202211012011.yaml
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/common/nm-ip-selectors.ts
  frontend/src/css/app.css
  frontend/src/types/plugin/plugin-type.ts
  frontend/src/views/plugin/plugin-rule/plugin-rule-create/deploy-target.vue
  frontend/src/views/plugin/plugin-rule/plugin-rule-create/index.vue
Labels: kind/feature

#1217 sprintfix: 修复IP选择器后台部分展示问题 (fixed #1040)
  apps/core/ipchooser/constants.py
  apps/core/ipchooser/handlers/base.py
  apps/core/ipchooser/handlers/topo_handler.py
  apps/core/ipchooser/query/resource.py
Labels: kind/bug, version/V2.2.X

#1218 sprintfix: 修复获取节点拓扑路径异常的问题 (fixed #1040)
  apps/core/ipchooser/tools/topo_tool.py
Labels: kind/bug, module/saas, version/V2.2.X

#1221 bugfix: 修复同步不到纯 IPv6 主机的问题 (fixed #1220)
  apps/node_man/periodic_tasks/sync_cmdb_host.py
  dev_log/2.2.32/crayon_202211071651.yaml
Labels: kind/bug, module/backend, version/V2.2.X

#1225 feature: 订阅详情接口支持过滤现存范围内执行快照 (closed #1222)
  apps/backend/subscription/handler.py
  apps/backend/subscription/serializers.py
  apps/backend/subscription/views.py
  dev_log/2.2.32/crayon_202211082006.yaml
Labels: kind/feature, module/backend, version/V2.2.X

#1227 optimization: 2.0 Agent 健康检查动作顺序调整 (closed #1226)
  dev_log/2.2.32/xcwang_202211091503.yaml
  script_tools/agent_tools/agent2/setup_agent.sh
  script_tools/agent_tools/agent2/setup_proxy.sh
Labels: module/backend, version/V2.2.X

#1231 sprintfix: 修复订阅详情接口没有过滤实际范围内实例的问题 (fixed #1222)
  apps/backend/subscription/handler.py
Labels: kind/feature, module/backend, version/V2.2.X

#1229 optimization: Excel模板动态导出(closed #1228)
  dev_log/2.2.32/daoqgong_202211091549.yaml
  frontend/src/views/agent/components/create-excel.ts
  frontend/src/views/agent/components/parser-excel.vue
  static/download/bk_nodeman_info.xlsx
  static/download/bk_nodeman_info_en.xlsx
  static/download/bk_nodeman_info_en_address.xlsx
  static/download/bk_nodeman_info_zh.xlsx
  static/download/bk_nodeman_info_zh_address.xlsx
Labels: kind/optimization

#1233 sprintfix: 修复订阅任务无 pipeline_id 流程误解析的问题 (fixed #1222)
  apps/backend/management/commands/transfer_old_sub.py
  apps/backend/subscription/handler.py
Labels: kind/bug, module/backend, version/V2.2.X

#1230 bugfix: 部分场景下 IPv6 地址校验不通过 (closed #1219)
  dev_log/2.2.32/daoqgong_202211111754.yaml
  frontend/src/common/form-check.ts
  frontend/src/common/regexp.ts
  frontend/src/components/setup-table/install-table.vue
  frontend/src/main.ts
  frontend/src/setup/encrypt.ts
  frontend/src/setup/filters.ts
  frontend/src/setup/i18n-setup.ts
  frontend/src/setup/index.ts
  frontend/src/setup/ipv6.ts
  frontend/src/setup/text-tool.ts
  frontend/src/store/modules/config.ts
  frontend/src/types/cloud/cloud.ts
  frontend/src/types/config/config.ts
  frontend/src/views/agent/agent-setup/agent-import.vue
  frontend/src/views/agent/agent-setup/agent-setup.vue
  frontend/src/views/agent/components/parser-excel.vue
  frontend/src/views/agent/config/setupTableConfig.ts
  frontend/src/views/cloud/cloud-channel/channel-edit.vue
  frontend/src/views/cloud/cloud-manager-add/cloud-manager-setup.vue
  frontend/src/views/cloud/cloud-manager-detail/cloud-manager-detail.vue
  frontend/src/views/cloud/components/sideslider-content-edit.vue
  frontend/src/views/global-config/gse-config/access-point-table.vue
  frontend/src/views/global-config/gse-config/set-access-point/access-point.vue
  frontend/src/views/global-config/gse-config/set-access-point/step-host.vue
  frontend/src/views/global-config/gse-config/set-access-point/step-info.vue
  frontend/src/vue-proto.d.ts
Labels: kind/bug

#1234 feature: 支持 IPv6 单栈场景 (closed #1223)
  apps/backend/agent/solution_maker.py
  apps/backend/agent/tools.py
  apps/backend/components/collections/agent_new/base.py
  apps/backend/components/collections/agent_new/check_policy_gse_to_proxy.py
  apps/backend/components/collections/agent_new/choose_access_point.py
  apps/backend/subscription/steps/agent_adapter/legacy.py
  apps/backend/tests/components/collections/agent_new/test_check_policy_gse_to_proxy.py
  apps/backend/tests/components/collections/agent_new/test_install.py
  apps/backend/tests/components/collections/agent_new/utils.py
  apps/mock_data/common_unit/host.py
  apps/node_man/models.py
  apps/node_man/serializers/ap.py
  apps/node_man/serializers/install_channel.py
  apps/node_man/utils/__init__.py
  apps/node_man/utils/endpoint.py
  apps/node_man/views/ap.py
  apps/utils/basic.py
  dev_log/2.2.32/crayon_202211111734.yaml
  script_tools/agent_tools/agent2/setup_agent.bat
  script_tools/agent_tools/agent2/setup_agent.sh
  script_tools/agent_tools/agent2/setup_proxy.sh
Labels: kind/feature, module/backend, module/saas, module/frontend, version/V2.2.X

#1236 sprintfix: IPV6引用错误问题修复 （fixed #1219)
  frontend/src/common/form-check.ts
Labels: kind/bug

#1240 sprintfix: IPV6 登录IP校验不通过问题（fixed #1219)
  frontend/src/views/agent/config/editTableConfig.ts
  frontend/src/views/agent/config/importTableConfig.js
Labels: kind/bug

#1241 bugfix: Proxy 安装信息留空确认后样式异常 (closed #1238)
  dev_log/2.2.32/daoqgong_202211151040.yaml
  frontend/src/components/setup-table/install-table.vue
Labels: kind/bug

#1244 bugfix: 修复 k8s v6 单栈部署 saas-api v6 地址无监听的问题 (fixed #970)
  bin/hooks/start_cmds/start-saas-api
  dev_log/2.2.32/crayon_202211161741.yaml
  support-files/kubernetes/helm/bk-nodeman/templates/migrate-jobs/db-migrate-job.yaml
  support-files/kubernetes/helm/bk-nodeman/templates/migrate-jobs/file-sync-migrate-job.yaml
  support-files/kubernetes/helm/bk-nodeman/values.yaml
Labels: kind/bug, module/build, version/V2.2.X

#1242 feature: Agent 2.0 GSE 文件服务对接 (closed #1239)
  apps/backend/components/collections/agent_new/check_policy_gse_to_proxy.py
  apps/backend/subscription/commons.py
  apps/backend/subscription/steps/agent_adapter/adapter.py
  apps/backend/subscription/steps/agent_adapter/config_context/context_dataclass.py
  apps/backend/subscription/steps/agent_adapter/config_context/context_helper.py
  apps/backend/subscription/steps/agent_adapter/config_templates.py
  apps/backend/subscription/tools.py
  apps/node_man/constants.py
  dev_log/2.2.32/crayon_202211161020.yaml
  script_tools/agent_tools/agent2/setup_proxy.sh
  script_tools/gsectl/proxy/linux/gsectl
Labels: kind/feature, module/backend, version/V2.2.X

#1245 sprintfix: 修复动态导出的excel模板boolean值识别不正确问题
  frontend/src/views/agent/components/create-excel.ts
Labels: kind/bug

#1247 bugfix: 资源配额 业务与模板ID相同时选中不正确 (closed #1246)
  dev_log/2.2.32/daoqgong_202211181013.yaml
  frontend/index-dev.html
  frontend/index.html
  frontend/src/components/exception/EmptyServiceBox.vue
  frontend/src/css/install-table.css
  frontend/src/i18n/en.js
  frontend/src/i18n/zh.js
  frontend/src/router/modules/plugin-manager.ts
  frontend/src/views/plugin/resource-quota/index.vue
  frontend/src/views/plugin/resource-quota/resource-tree-item.vue
  frontend/src/views/plugin/resource-quota/resource-tree.vue
Labels: kind/bug

#1252 bugfix: Windows 通过 IPv6 远程执行命令报错：Can't find a valid stringBinding to connect (fixed #1251)
  apps/backend/agent/solution_maker.py
  apps/backend/utils/wmi.py
  dev_log/2.2.32/crayon_202211211658.yaml
Labels: kind/bug, module/backend, version/V2.2.X

#1256 feature: 新增 BK_CC_HOST 环境变量用于前端跳转逻辑 (closed #1255)
  common/context_processors.py
  config/default.py
  dev_log/2.2.32/crayon_202211211745.yaml
  env/__init__.py
  support-files/kubernetes/helm/bk-nodeman/README.md
  support-files/kubernetes/helm/bk-nodeman/templates/configmaps/env-configmap.yaml
  support-files/kubernetes/helm/bk-nodeman/values.yaml
Labels: module/saas, version/V2.2.X

#1254 optimization: Helm Charts InitContainers 容器名称去除 revision 后缀 (closed #1253)
  dev_log/2.2.32/crayon_202211211735.yaml
  support-files/kubernetes/helm/bk-nodeman/templates/_helpers.tpl
  support-files/kubernetes/helm/bk-nodeman/templates/migrate-jobs/file-sync-migrate-job.yaml
  support-files/kubernetes/helm/bk-nodeman/templates/saas-api/deployment.yaml
Labels: kind/optimization, module/build, version/V2.2.X

#1262 sprintfix: Job AgentID 同步等待，筛选可选项修改
  apps/backend/subscription/steps/agent.py
  apps/core/ipchooser/constants.py
  apps/core/ipchooser/tools/base.py
  apps/node_man/handlers/meta.py
  apps/node_man/tests/test_handlers/test_meta.py
Labels: kind/bug, kind/feature, version/V2.2.X

#1263 sprintfix: 调整为仅主插件操作需要前置下发操作脚本
  apps/backend/components/collections/plugin.py
  apps/backend/plugin/manager.py
  apps/backend/subscription/steps/plugin.py
Labels: kind/bug, module/backend, version/V2.2.X

#1266 sprintfix: 适配 CMDB 主机寻址方式枚举值变更 (fixed #1260)
  apps/node_man/constants.py
Labels: kind/bug, module/saas, version/V2.2.X

#1268 sprintfix: 修复 Windows 指定不存在 reload.bat 文件的问题 (fixed #471)
  apps/backend/components/collections/plugin.py
Labels: kind/bug, module/backend, version/V2.2.X

#1267 optimization: IPv6 交互体验全面优化(closed #1248)
  dev_log/2.2.32/daoqgong_202211231446.yaml
  frontend/package-lock.json
  frontend/package.json
  frontend/src/common/regexp.ts
  frontend/src/common/util.ts
  frontend/src/components/common/nm-ip-selectors.ts
  frontend/src/config/config.ts
  frontend/src/css/app.css
  frontend/src/css/install-table.css
  frontend/src/types/agent/agent-type.ts
  frontend/src/types/index.ts
  frontend/src/types/plugin/plugin-type.ts
  frontend/src/views/agent/agent-list.vue
  frontend/src/views/agent/components/parser-excel.vue
  frontend/src/views/agent/config/editTableConfig.ts
  frontend/src/views/agent/config/importTableConfig.js
  frontend/src/views/agent/config/setupTableConfig.ts
  frontend/src/views/plugin/plugin-list/plugin-list-operate.vue
  frontend/src/views/plugin/plugin-list/plugin-list-table.vue
  frontend/src/views/plugin/plugin-rule/plugin-rule-create/perform-preview.vue
  frontend/src/views/task/task-detail-new.vue
  frontend/src/views/task/task-detail-table.vue
  frontend/src/views/task/task-log.vue
Labels: kind/optimization

#1270 sprintfix: 接入点commit - server数据不正确问题
  frontend/src/views/global-config/gse-config/set-access-point/step-host.vue
  frontend/src/views/global-config/gse-config/set-access-point/step-info.vue
Labels: kind/bug

#1273 bugfix: 修复 2.0 Proxy 重装灰度判断错误的问题 (fixed #1272)
  apps/node_man/handlers/job.py
  apps/node_man/serializers/job.py
  apps/node_man/tests/test_handlers/test_job.py
  apps/node_man/views/job.py
  dev_log/2.2.32/crayon_202211241423.yaml
Labels: kind/bug, module/saas, version/V2.2.X

#1274 bugfix: 修复接入点更新后端口配置被重置 (fixed #1271)
  apps/node_man/views/ap.py
  dev_log/2.2.32/crayon_202211241426.yaml
Labels: kind/bug, module/saas, version/V2.2.X

#1275 optimization: 作业平台文件源别名规范调整 (closed #1269)
  apps/core/files/file_source.py
  dev_log/2.2.32/crayon_202211241432.yaml
Labels: kind/optimization, module/backend, version/V2.2.X

#1276 sprintfix: 修复脚本冗余传输 / Windows 脚本初始化失败的问题 (fixed #471)
  apps/backend/components/collections/plugin.py
  script_tools/plugin_scripts/update_binary.bat
  script_tools/plugin_scripts/update_binary.sh
Labels: kind/feature, module/backend, version/V2.2.X

#1287 feature: 安装动态寻址主机校验 Agent 存活校验及 AgentID 重置判定 (#1281)
  apps/adapters/api/gse/v1.py
  apps/backend/agent/solution_maker.py
  apps/backend/agent/tools.py
  apps/backend/components/collections/agent_new/base.py
  apps/backend/components/collections/agent_new/bind_host_agent.py
  apps/backend/subscription/steps/agent.py
  apps/backend/subscription/steps/agent_adapter/base.py
  apps/backend/subscription/views.py
  apps/node_man/handlers/job.py
  apps/node_man/handlers/validator.py
Labels: kind/feature, module/saas, module/build, version/V2.2.X

#1288 sprintfix: 创建订阅报错 "can not get ip in obj type host info"
  apps/backend/subscription/steps/plugin.py
Labels: kind/bug, module/backend, version/V2.2.X

#1293 feature: Proxy Nginx 配置 v6 支持 (closed #1289)
  dev_log/2.2.32/xcwang_202211292306.yaml
  script_tools/start_nginx.sh.tpl
Labels: version/V2.2.X, module/script

#1291 feature: P-Agent 安装 IPv6 场景适配 (closed #1290)
  apps/backend/agent/solution_maker.py
  apps/backend/agent/tools.py
  apps/backend/components/collections/agent_new/install.py
  dev_log/2.2.32/crayon_202211292126.yaml
  script_tools/agent_tools/agent2/setup_agent.sh
  script_tools/agent_tools/agent2/setup_proxy.sh
  script_tools/setup_pagent.py
  script_tools/start_nginx.sh.tpl
Labels: kind/feature, module/backend, version/V2.2.X, module/script

#1296 optimization: 安装动态寻址主机校验 Agent 存活实时校验
  apps/adapters/api/gse/v2.py
  apps/node_man/constants.py
  apps/node_man/handlers/host.py
  apps/node_man/handlers/validator.py
  apps/node_man/serializers/job.py
Labels: kind/feature, module/saas, version/V2.2.X

#1297 sprintfix: ip-selector版本升级
  frontend/package-lock.json
  frontend/package.json
Labels: kind/bug
