Repository TencentBlueKing/bk-nodeman, pull requests merged in 2022-06, with the labels that each got.

#801 optimization: Agent新增事件告警配置 (closed #799)
  apps/backend/readme.md
  apps/backend/views.py
  dev_log/2.2.15/xcwang_202205311636.yaml
Labels: kind/optimization, module/backend, version/V2.2.X

#812 optimization: 消除运行环境差异 (closed #779)
  apps/mock_data/common_unit/host.py
  apps/node_man/constants.py
  apps/node_man/migrations/0023_init_proxy_package.py
  config/default.py
  dev_log/2.1.348/crayon_202109242000.yaml
  dev_log/2.2.16/xcwang_202206071506.yaml
  docs/release.md
  release/V2.1.348_20210928.md
Labels: kind/optimization, module/saas, version/V2.2.X

#820 bugfix: 版本日志展示位置调整(closed #756)
  dev_log/2.2.16/daoqgong_202206070957.yaml
  frontend/src/components/common/log-version.vue
  frontend/src/css/app.css
Labels: kind/bug, module/saas, version/V2.2.X

#818 optimization: 插件包解析页面 支持系统 列展示操作系统类型 (closed #711)
  dev_log/2.2.16/daoqgong_202206071021.yaml
  frontend/src/store/modules/main.ts
  frontend/src/views/plugin/plugin-package/plugin-package-parsing.vue
Labels: kind/optimization, module/saas, version/V2.2.X

#811 optimization: Agent 管理「业务拓扑」支持拖动改变宽度(closed #470)
  dev_log/2.2.16/daoqgong_202206071050.yaml
  frontend/src/css/app.css
  frontend/src/views/agent/agent-list.vue
Labels: kind/optimization, module/frontend, version/V2.2.X

#816 optimization: Linux 相关 Agent 安装服务探测优化 (closed #774)
  dev_log/2.2.16/xcwang_202206072053.yaml
  script_tools/setup_agent.sh
  script_tools/setup_proxy.sh
Labels: kind/optimization, version/V2.2.X, module/script

#824 sprintfix: 框架依赖环境变量调整错误
  config/default.py
Labels: kind/bug

#826 sprintfix: Proxy 安装没有探测 Gse 服务
  script_tools/setup_proxy.sh
Labels: kind/bug, version/V2.2.X, module/script

#828 optimization: 更新 Charts 依赖 (closed #827)
  dev_log/2.2.17/crayon_202206091609.yaml
  support-files/kubernetes/helm/bk-nodeman/Chart.lock
  support-files/kubernetes/helm/bk-nodeman/Chart.yaml
Labels: module/build, version/V2.2.X, kind/dependencies

#834 optimization: 批量UI统一
  frontend/src/views/agent/agent-list.vue
  frontend/src/views/plugin/plugin-list/plugin-list-operate.vue
Labels: kind/feature

#837 optimization: 插件操作提示UI优化
  frontend/src/i18n/en.js
  frontend/src/i18n/zh.js
  frontend/src/views/plugin/plugin-list/plugin-list-operate.vue
Labels: kind/optimization

#851 optimization: 登录跳转取消弹框 (closed #843)
  dev_log/2.2.18/daoqing_2022060151546.yaml
  frontend/src/App.vue
Labels: kind/optimization

#864 optimization: Agent 状态查询兼容 NOT FOUND 场景 (closed #863)
  apps/adapters/api/gse/v2.py
Labels: kind/optimization, module/backend, module/saas, version/V2.2.X

#875 optimization: 手动安装引导页去除冗余提示信息 (closed #855)
  dev_log/2.2.18/daoqing_202206231831.yaml
  frontend/src/views/task/task-detail-slider.vue
  frontend/src/views/task/task-detail.vue
Labels: kind/optimization

#872 bugfix: Agent 安装表单无法选择操作系统 (closed #865)
  dev_log/2.2.18/daoqing_202206231858.yaml
  frontend/src/router/index.ts
Labels: kind/bug

#877 bugfix: 修复 KubeVersion < 1.18-0 ingress 渲染错误：Service(nodeman/bk-nodeman-saas-api) do not have port 80. 的问题 (fixed #876)
  dev_log/2.2.18/crayon_202206281022.yaml
  support-files/kubernetes/helm/bk-nodeman/templates/ingress.yaml
Labels: kind/bug, module/build, version/V2.2.X

#879 feature: 支持 bkmonitorproxy 的资源配额设置 (closed #868)
  apps/node_man/handlers/plugin_v2.py
  dev_log/2.2.18/crayon_202206281132.yaml
Labels: kind/optimization, module/saas, version/V2.2.X

#880 optimization: 部署策略展示顺序优化 (closed#856 closed#857)
  dev_log/2.2.18/daoqing_202206291110.yaml
  frontend/src/types/plugin/plugin-type.ts
  frontend/src/views/plugin/plugin-rule/plugin-rule.vue
Labels: kind/bug, kind/feature

#881 optimization: 部署策略展示顺序优化 (closed #856 closed #857)
  apps/backend/subscription/serializers.py
  apps/backend/subscription/views.py
  apps/node_man/constants.py
  apps/node_man/serializers/policy.py
  dev_log/2.2.18/daoqing_202206291110.yaml
  frontend/src/types/plugin/plugin-type.ts
  frontend/src/views/plugin/plugin-rule/plugin-rule.vue
Labels: kind/optimization, module/backend, module/frontend, version/V2.2.X

#871 bugfix: Windows 拼接注册服务名称错误 (closed #870)
  dev_log/2.2.18/xcwang_202206241106.yaml
  script_tools/setup_agent.bat
Labels: kind/bug, version/V2.2.X
