Repository TencentBlueKing/bk-nodeman, pull requests merged in 2023-02, with the labels that each got.

#1427 feature: 调用链路国际化打通 (closed #1333)
  apps/backend/plugin/handler.py
  apps/backend/plugin/tools.py
  apps/backend/plugin/views.py
  apps/node_man/handlers/job.py
  apps/node_man/views/plugin_v2.py
  common/api/base.py
Labels: module/backend, module/saas

#1429 feature: 支持单次执行进程的插件导入及部署 (closed #1428)
  apps/backend/components/collections/plugin.py
  apps/backend/plugin/tools.py
  apps/backend/tests/plugin/utils.py
  apps/mock_data/common_unit/plugin.py
  apps/node_man/constants.py
  apps/node_man/migrations/0067_auto_20230201_1621.py
  apps/node_man/models.py
Labels: module/backend

#1430 sprintfix: 国际化修复 (fixed #1333 fixed #1332)
  apps/backend/agent/solution_maker.py
  apps/backend/components/collections/agent_new/install.py
  apps/backend/components/collections/subsubscription.py
  apps/backend/plugin/views.py
  apps/backend/subscription/steps/agent.py
  apps/backend/subscription/steps/plugin.py
  apps/backend/subscription/tasks.py
  apps/backend/tests/components/collections/agent_new/utils.py
  apps/core/ipchooser/handlers/base.py
  apps/middlewares.py
  apps/mock_data/common_unit/host.py
  apps/node_man/constants.py
  apps/node_man/handlers/cloud.py
  apps/node_man/handlers/cmdb.py
  apps/node_man/handlers/host.py
  apps/node_man/handlers/host_v2.py
  apps/node_man/handlers/plugin.py
  common/api/base.py
  config/default.py
  locale/en/LC_MESSAGES/django.mo
  locale/en/LC_MESSAGES/django.po
Labels: kind/feature, version/V2.2.X

#1432 sprintfix: 重装主机 - IP文本省略时支持tooltips(closed #1382)
  frontend/src/components/setup-table/install-table.vue
Labels: kind/bug

#1434 sprintfix: IPv4文本统一改为IP( closed #1399)
  frontend/src/components/setup-table/table-header-tip.vue
  frontend/src/i18n/en.js
  frontend/src/i18n/zh.js
  frontend/src/views/agent/components/create-excel.ts
  frontend/src/views/agent/config/editTableConfig.ts
  frontend/src/views/agent/config/importTableConfig.js
  frontend/src/views/agent/config/setupTableConfig.ts
  frontend/src/views/cloud/cloud-manager-detail/cloud-detail-table.vue
  frontend/src/views/cloud/components/sideslider-content-edit.vue
  frontend/src/views/cloud/config/netTableConfig.ts
Labels: kind/optimization

#1437 bugfix: 页面权限问题修复(fixed #1413)
  frontend/src/router/index.ts
  frontend/src/views/agent/agent-setup/agent-import.vue
  frontend/src/views/agent/config/importTableConfig.js
  frontend/src/views/plugin/resource-quota/index.vue
Labels: kind/bug

#1440 sprintfix: 后台支持 IP/IPv6 主机属性的指定返回 (fixed #1381)
  apps/core/ipchooser/tools/base.py
  apps/node_man/handlers/host.py
  apps/node_man/handlers/plugin.py
  apps/node_man/serializers/base.py
  apps/node_man/serializers/host.py
  apps/node_man/serializers/host_v2.py
  apps/node_man/serializers/plugin.py
  apps/node_man/serializers/plugin_v2.py
  apps/node_man/tests/test_handlers/test_host.py
  apps/node_man/tests/test_handlers/test_plugin.py
Labels: kind/bug, kind/feature

#1435 sprintfix: agent安装提示 缺省替换为 未填写(closed #1408)
  frontend/src/i18n/en.js
  frontend/src/i18n/zh.js
Labels: kind/optimization

#1443 sprintfix: 2.0 Proxy Data endpoint 渲染有误 (fixed #1340)
  apps/backend/agent/tools.py
  apps/backend/subscription/steps/agent_adapter/config_context/context_helper.py
Labels: kind/bug, module/backend

#1446 sprintfix: IP 选择器获取自定义层级 Agent 状态统计及主机查询异常 (fixed #1444)
  apps/core/ipchooser/tools/base.py
Labels: module/saas

#1449 feature: /cloud/ 接口 proxies 新增 IPv6 及 AgentID 字段 (closed #1448)
  apps/node_man/handlers/cloud.py
Labels: module/saas

#1450 feature: 支持 IPv6 后的复制交互优化（closed #1438）
  frontend/src/common/form-check.ts
  frontend/src/common/test-anchor.ts
  frontend/src/components/common/associate-list.vue
  frontend/src/components/common/copy-dropdown.vue
  frontend/src/components/setup-table/table-header-tip.vue
  frontend/src/css/app.css
  frontend/src/i18n/en.js
  frontend/src/i18n/zh.js
  frontend/src/setup/ipv6.ts
  frontend/src/types/agent/agent-type.ts
  frontend/src/types/task/task.ts
  frontend/src/views/agent/agent-list.vue
  frontend/src/views/agent/components/create-excel.ts
  frontend/src/views/agent/config/editTableConfig.ts
  frontend/src/views/agent/config/importTableConfig.js
  frontend/src/views/agent/config/setupTableConfig.ts
  frontend/src/views/cloud/cloud-manager-detail/cloud-detail-table.vue
  frontend/src/views/cloud/cloud-manager.vue
  frontend/src/views/cloud/components/sideslider-content-edit.vue
  frontend/src/views/cloud/config/netTableConfig.ts
  frontend/src/views/cloud/config/proxy-detail-config.js
  frontend/src/views/plugin/plugin-list/plugin-list-operate.vue
  frontend/src/views/plugin/plugin-list/plugin-list-table.vue
  frontend/src/views/plugin/plugin-list/plugin-list.vue
  frontend/src/views/task/task-detail-new.vue
  frontend/src/views/task/task-detail-table.vue
Labels: kind/feature

#1451 sprintfix: Agent安装IPv4/IPv6二选一必填提醒错误(closed #1403)
  frontend/src/components/common/verify-input.vue
  frontend/src/components/setup-table/install-table.vue
Labels: kind/bug

#1436 sprintfix: ip选择器版本升级(closed #1391 closed #1393 closed #1391 closed #1…
  frontend/package-lock.json
  frontend/package.json
Labels: kind/bug

#1459 feat: i18n问题修复(closed #1426)
  frontend/src/components/common/navigation.vue
  frontend/src/components/common/strategy-table.vue
  frontend/src/css/app.css
  frontend/src/i18n/en.js
  frontend/src/i18n/zh.js
  frontend/src/router/navigation-config.ts
  frontend/src/store/modules/main.ts
  frontend/src/types/plugin/plugin-type.ts
  frontend/src/views/agent/agent-list.vue
  frontend/src/views/agent/agent-setup/agent-import.vue
  frontend/src/views/global-config/gse-config/access-point-table.vue
  frontend/src/views/plugin/plugin-list/plugin-list.vue
  frontend/src/views/plugin/plugin-package/plugin-detail.vue
  frontend/src/views/plugin/plugin-package/plugin-package-parsing.vue
  frontend/src/views/plugin/plugin-package/plugin-package-table.vue
  frontend/src/views/plugin/plugin-rule/plugin-rule-choose/plugin-rule-choose.vue
Labels: kind/optimization

#1457 feature: 支持 ESB / APIGW 双公钥 (closed #1369)
  apps/authentication.py
  apps/middlewares.py
  apps/node_man/apps.py
  apps/utils/local.py
  config/default.py
  env/__init__.py
  env/paas_version_diff/__init__.py
  requirements.txt
Labels: kind/feature

#1458 bugfix: 手动安装指引 - 任务历史场景覆盖(closed #1421)
  frontend/src/i18n/en.js
  frontend/src/i18n/zh.js
  frontend/src/views/task/task-detail-table.vue
  frontend/src/views/task/task-log.vue
Labels: kind/bug
