Repository TencentBlueKing/bk-nodeman, pull requests merged in 2023-07, with the labels that each got.

#1639 sprintfix: 补充翻译校正(closed #1545)
  frontend/build/tsconfig.json
  frontend/build/webpack.base.conf.ts
  frontend/build/webpack.dev.conf.ts
  frontend/build/webpack.prod.conf.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/src/common/form-check.ts
  frontend/src/components/common/nav-side.vue
  frontend/src/components/common/nm-exception.vue
  frontend/src/components/common/nm-ip-selectors.ts
  frontend/src/components/common/strategy-table.vue
  frontend/src/components/setup-table/install-table.vue
  frontend/src/components/setup-table/table-header-tip.vue
  frontend/src/i18n/en.js
  frontend/src/i18n/zh.js
  frontend/src/router/modules/agent-manager.ts
  frontend/src/router/modules/cloud-manager.ts
  frontend/src/router/modules/global-config.ts
  frontend/src/router/modules/plugin-manager.ts
  frontend/src/router/modules/plugin-old.ts
  frontend/src/router/modules/task-history-new.ts
  frontend/src/router/navigation-config.ts
  frontend/src/setup/i18n-setup.ts
  frontend/src/views/agent/agent-setup/agent-import.vue
  frontend/src/views/agent/agent-setup/agent-setup.vue
  frontend/src/views/cloud/cloud-manager-add/cloud-manager-add.vue
  frontend/src/views/cloud/cloud-manager-add/cloud-manager-setup.vue
  frontend/src/views/plugin/plugin-rule/plugin-rule-create/pluginConfig.ts
  frontend/src/views/plugin/resource-quota/edit.vue
  frontend/src/views/plugin/resource-quota/index.vue
  frontend/src/views/task/task-list.vue
  frontend/static/lib-manifest.json
  frontend/static/lib.bundle.js
  frontend/static/lib.bundle.js.LICENSE.txt
  frontend/tsconfig.json
  static/index.html
Labels: kind/bug, kind/feature

#1647 sprintfix: 国际化翻译校正 (closed #1445)
  frontend/src/css/app.css
  frontend/src/i18n/en.js
Labels: kind/bug

#1657 sprintfix: 调整国际化切换规则 (closed #1445)
  frontend/index-dev.html
  frontend/index.html
  frontend/src/components/common/navigation.vue
Labels: kind/dependencies

#1667 feature: 根据 Proxy 实时 Agent 状态选择上游节点 (closed #1659)
  apps/backend/agent/tasks.py
  apps/backend/agent/tools.py
  apps/backend/components/collections/agent_new/base.py
  apps/backend/components/collections/agent_new/choose_access_point.py
  apps/backend/components/collections/agent_new/push_agent_pkg_to_proxy.py
  apps/backend/subscription/steps/agent.py
  apps/backend/subscription/steps/agent_adapter/adapter.py
  apps/backend/subscription/steps/agent_adapter/config_context/context_helper.py
  apps/backend/subscription/steps/agent_adapter/legacy.py
  apps/backend/tests/components/collections/agent_new/test_choose_access_point.py
  apps/backend/tests/components/collections/agent_new/test_install.py
  apps/backend/tests/components/collections/agent_new/test_push_agent_pkg_to_proxy.py
  apps/backend/tests/components/collections/agent_new/test_render_and_push_gse_config.py
  apps/backend/tests/components/collections/agent_new/utils.py
  apps/mock_data/api_mkd/gse/unit.py
  apps/mock_data/api_mkd/gse/utils.py
  apps/node_man/models.py
  locale/en/LC_MESSAGES/django.mo
  locale/en/LC_MESSAGES/django.po
Labels: pr/reviewable

#1638 feature: 双 Agent / Proxy 安装支持 (closed #1592)
  apps/backend/agent/manager.py
  apps/backend/agent/solution_maker.py
  apps/backend/agent/tools.py
  apps/backend/api/constants.py
  apps/backend/components/collections/agent_new/base.py
  apps/backend/components/collections/agent_new/check_policy_gse_to_proxy.py
  apps/backend/components/collections/agent_new/components.py
  apps/backend/components/collections/agent_new/install.py
  apps/backend/components/collections/agent_new/install_other_agent.py
  apps/backend/subscription/steps/agent.py
  apps/backend/tests/view/base.py
  apps/backend/tests/view/test_get_gse_config.py
  apps/backend/views.py
  apps/core/gray/constants.py
  apps/core/gray/tools.py
  apps/node_man/handlers/validator.py
  apps/node_man/models.py
  apps/node_man/serializers/job.py
  apps/node_man/views/job.py
  common/api/modules/bk_node.py
  locale/en/LC_MESSAGES/django.mo
  locale/en/LC_MESSAGES/django.po
Labels: pr/reviewable

#1669 bugfix: Proxy 状态不准确 (closed #1668)
  apps/node_man/handlers/host.py
Labels: pr/reviewable

#1652 feature: 提供国密支持 (closed #1649)
  .github/workflows/codecov.yml
  apps/backend/agent/solution_maker.py
  apps/backend/subscription/serializers.py
  apps/backend/tests/view/base.py
  apps/backend/views.py
  apps/core/encrypt/admin.py
  apps/core/encrypt/constants.py
  apps/core/encrypt/handlers.py
  apps/core/encrypt/migrations/0002_auto_20230712_1436.py
  apps/core/encrypt/models.py
  apps/core/encrypt/serializers.py
  apps/core/encrypt/tests/test_handlers.py
  apps/core/encrypt/tests/test_views.py
  apps/core/encrypt/tests/utils.py
  apps/core/encrypt/views.py
  apps/node_man/apps.py
  apps/node_man/handlers/job.py
  apps/node_man/migrations/0001_initial.py
  apps/node_man/models.py
  apps/node_man/serializers/host.py
  apps/node_man/serializers/job.py
  apps/node_man/tests/test_handlers/test_job.py
  apps/node_man/tests/test_tools/test_host.py
  apps/node_man/tests/utils.py
  apps/node_man/tools/host.py
  apps/utils/encrypt/crypto.py
  apps/utils/encrypt/key.py
  config/default.py
  env/__init__.py
  env/constants.py
  requirements.txt
Labels: pr/reviewable

#1666 feat: 国密前端支持(closed #1660 #1650)
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.vue
  frontend/src/setup/RSA.ts
  frontend/src/setup/SM2.ts
  frontend/src/setup/index.ts
  frontend/src/setup/safety.ts
  frontend/src/store/modules/main.ts
  frontend/src/types/index.ts
  frontend/src/views/agent/agent-setup/agent-import.vue
  frontend/src/views/agent/agent-setup/agent-setup.vue
  frontend/src/views/cloud/cloud-manager-add/cloud-manager-setup.vue
  frontend/src/views/cloud/components/sideslider-content-edit.vue
  frontend/src/vue-proto.d.ts
Labels: kind/feature, pr/reviewable

#1673 feat: zk脱敏交互优化 (closed #1650)
  frontend/src/components/setup-table/input-type.vue
  frontend/src/components/setup-table/install-input-type.vue
  frontend/src/components/setup-table/install-table.vue
  frontend/src/components/setup-table/table-header.vue
  frontend/src/store/modules/config.ts
  frontend/src/views/global-config/gse-config/set-access-point/step-host.vue
  frontend/src/views/global-config/gse-config/set-access-point/step-info.vue
Labels: kind/feature

#1694 sprintfix: 升级 blueapps 版本 (closed #1689)
  requirements.txt
Labels: pr/reviewable

#1688 sprintfix: 二进制部署场景下取 BKPAAS_BK_DOMAIN 为主域名
  env/__init__.py
  support-files/kubernetes/helm/bk-nodeman/templates/configmaps/env-configmap.yaml
Labels: grayed, pr/reviewable

#1656 optimization: 支持周期删除订阅执行日志 (closed #1348)
  apps/backend/periodic_tasks/__init__.py
  apps/backend/periodic_tasks/clean_pipeline_data.py
  apps/backend/periodic_tasks/clean_subscription_data.py
  apps/backend/tests/periodic_tasks/test_clean_subscription_data.py
  apps/node_man/models.py
Labels: pr/reviewable

#1702 optimization: 分页时展示 Agent 实时状态 (closed #752)
  apps/core/ipchooser/tools/host_tool.py
  apps/node_man/handlers/host.py
  apps/node_man/periodic_tasks/sync_agent_status_task.py
Labels: pr/reviewable

#1665 feature: 任务历史支持 ip 过滤(closed #1631)
  apps/node_man/handlers/job.py
  apps/node_man/handlers/meta.py
  apps/node_man/serializers/job.py
  apps/node_man/tests/test_handlers/test_job.py
  apps/node_man/tests/utils.py
  apps/node_man/tools/job.py
Labels: pr/reviewable
