Repository TencentBlueKing/bk-nodeman, pull requests merged in 2023-03, with the labels that each got.

#1468 feature: 配置模板支持主机动态渲染 (closed #1466)
  apps/backend/subscription/render_functions.py
  apps/backend/subscription/steps/agent.py
  apps/node_man/handlers/validator.py
Labels: kind/feature

#1472 bugfix: 安装通道主机状态展示异常(closed TencentBlueKing#1351)
  frontend/src/views/cloud/cloud-manager-detail/cloud-manager-detail.vue
Labels: kind/bug

#1470 sprintfix: 规范问题补充
  frontend/src/components/common/nm-exception.vue
  frontend/src/css/app.css
  frontend/src/views/agent/agent-list.vue
  frontend/src/views/cloud/cloud-manager-detail/cloud-detail-nav.vue
  frontend/src/views/cloud/cloud-manager.vue
  frontend/src/views/plugin/plugin-list/plugin-list-table.vue
  frontend/src/views/plugin/plugin-list/plugin-list.vue
  frontend/src/views/plugin/plugin-package/index.vue
  frontend/src/views/plugin/plugin-package/plugin-package-table.vue
  frontend/src/views/plugin/plugin-rule/plugin-rule-list/plugin-rule-table.vue
  frontend/src/views/plugin/plugin-rule/plugin-rule.vue
  frontend/src/views/task/task-detail-new.vue
  frontend/src/views/task/task-detail-table.vue
  frontend/src/views/task/task-list-table.vue
  frontend/src/views/task/task-list.vue
Labels: kind/bug

#1475 sprintfix: 增加主机节点的场景 (closed #1466)
  apps/backend/subscription/render_functions.py
Labels: module/backend

#1477 bugfix: 修复版本标签更新指向版本无效的问题 (closed #1476)
  apps/core/tag/views.py
Labels: kind/bug

#1486 feat: IP选择器版本升级(closed #1394 closed #1383)
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/common/nm-ip-selectors.ts
Labels: kind/bug, kind/feature

#1485 feature: 英文翻译校正(closed #1484)
  frontend/src/i18n/en.js
  frontend/src/i18n/zh.js
  frontend/src/views/agent/agent-setup/agent-import.vue
  frontend/src/views/agent/agent-setup/agent-setup.vue
  frontend/src/views/agent/config/editTableConfig.ts
  frontend/src/views/agent/config/importTableConfig.js
  frontend/src/views/agent/config/setupTableConfig.ts
  frontend/src/views/cloud/cloud-manager-add/cloud-manager-setup.vue
Labels: for test

#1492 sprintfix: 修复 Proxy 重载任务启动报错的问题 (fixed #1332)
  apps/backend/subscription/steps/agent.py
Labels: kind/bug
