Repository TencentBlueKing/bk-nodeman, pull requests merged in 2023-06, with the labels that each got.

#1589 docs: 功能文档更新 (closed #1588)
  docs/solution/gse2-gray.md
  docs/solution/how-to-install-agent2.md
  support-files/kubernetes/helm/bk-nodeman/templates/NOTES.txt
Labels: module/docs

#1593 sprintfix: 文本省略规范 表头参数问题修复(closed #1445)
  frontend/src/components/common/nm-column.vue
Labels: kind/bug

#1596 feat(front): 代码检查 package 依赖更新(closed #1594)
  frontend/package-lock.json
  frontend/package.json
Labels: kind/feature

#1597 sprintfix: 补充翻译校正(closed #1545)
  frontend/src/i18n/en.js
  frontend/src/i18n/zh.js
Labels: kind/docs, kind/optimization

#1610 sprintfix: 优化proxy安装表格宽度(closed #1545)
  frontend/src/components/setup-table/install-table.vue
Labels: kind/bug

#1615 sprintfix: 勾选IP翻译校正 (closed #1545)
  frontend/src/i18n/en.js
Labels: kind/bug
