Repository TencentBlueKing/bk-nodeman, pull requests merged in 2023-04, with the labels that each got.

#1488 sprintfix: 英文翻译问题补充 & ip选择器支持国际化 (closed #1484)
  frontend/package-lock.json
  frontend/package.json
  frontend/src/common/util.ts
  frontend/src/components/common/tips.vue
  frontend/src/i18n/en.js
  frontend/src/i18n/zh.js
  frontend/src/views/cloud/cloud-channel/index.vue
  frontend/src/views/plugin/plugin-list/plugin-list-table.vue
  frontend/src/views/plugin/plugin-package/plugin-detail.vue
  frontend/src/views/plugin/plugin-rule/plugin-rule-choose/rule-type.vue
  frontend/src/views/task/task-detail-slider.vue
  frontend/src/views/task/task-detail-table.vue
  frontend/src/views/task/task-list-filter.vue
  frontend/src/views/task/task-log.vue
  frontend/static/doc/install_channel_en.md
  frontend/static/doc/install_channel_zh.md
Labels: kind/bug, kind/feature

#1503 fix: 更新 Proxy 密钥所保存的密钥信息有误(closed #139)
  frontend/src/views/cloud/components/sideslider-content-edit.vue
Labels: kind/bug

#1504 fix: 安装表格默认值为false时初始化不正确(closed #1497)
  frontend/src/components/setup-table/install-table.vue
Labels: kind/bug

#1505 fix: 插件包列表已部署节点数量展示异常(closed #1489)
  frontend/src/views/plugin/plugin-package/index.vue
Labels: kind/bug

#1519 sprintfix: 文本省略规范补充(closed #1445)
  frontend/src/components/setup-table/install-table.vue
  frontend/src/css/app.css
  frontend/src/views/agent/agent-setup/agent-import.vue
Labels: kind/bug

#1522 optimization: k8s api 模块启动优化 (closed #1521)
  support-files/kubernetes/helm/bk-nodeman/templates/backend-api/deployment.yaml
  support-files/kubernetes/helm/bk-nodeman/templates/saas-api/deployment.yaml
Labels: kind/optimization

#1532 sprintfix: 修复部分灰度问题
  apps/backend/subscription/steps/agent_adapter/config_context/context_helper.py
  apps/core/gray/handlers.py
  apps/node_man/constants.py
Labels: kind/bug
