Repository TencentBlueKing/bk-nodeman, pull requests merged in 2023-01, with the labels that each got.

#1378 bugfix: 资源配额 - 初始化一直loading (closed #1377)
  frontend/src/views/agent/agent-setup/agent-setup.vue
  frontend/src/views/cloud/cloud-manager-add/cloud-manager-setup.vue
  frontend/src/views/plugin/resource-quota/index.vue
Labels: kind/bug

#1376 bugfix: 安装表格 - 只读属性被批量修改 (closed #1372)
  frontend/src/components/setup-table/install-table.vue
Labels: kind/bug

#1373 docs: 容器化场景下新增接入点说明文档 (closed #1304)
  docs/resource/img/nodeman_k8s-接入点地址漂移.png
  docs/solution/solution_accesspoint_address_drift.md
Labels: kind/docs

#1415 bugfix: 修复订阅更新接口 steps 更新不符合预期的问题 (fixed #1002)
  apps/backend/subscription/views.py
Labels: module/backend

#1390 sprintfix: 安装表格 - 只读属性关闭批量修改入口 (closed #1372)
  frontend/src/components/setup-table/install-table.vue
  frontend/src/types/index.ts
  frontend/src/views/agent/config/editTableConfig.ts
Labels: kind/bug

#1416 sprintfix: 资源配额 - 初始化一直loading (closed #1377)
  frontend/src/router/modules/plugin-manager.ts
  frontend/src/store/modules/plugin-new.ts
  frontend/src/views/plugin/resource-quota/index.vue
  frontend/src/views/plugin/resource-quota/resource-tree-item.vue
  frontend/src/views/plugin/resource-quota/tree-fn.ts
Labels: kind/bug

#1418 bugfix: 修复云区域变更为直连区域后节点类型错误的问题 (fixed #1417)
  apps/node_man/periodic_tasks/sync_cmdb_host.py
Labels: module/backend

#1419 sprintfix: 修复探测文件服务到 2.0 Proxy 10020/10030 端口不通的问题 (fixed #1239)
  apps/backend/components/collections/agent_new/check_policy_gse_to_proxy.py
  apps/backend/tests/components/collections/agent_new/test_check_policy_gse_to_proxy.py
  apps/backend/tests/components/collections/agent_new/test_push_agent_pkg_to_proxy.py
  apps/backend/tests/components/collections/agent_new/utils.py
  apps/node_man/constants.py
Labels: module/backend
