Repository TencentBlueKing/bk-nodeman, pull requests merged in 2023-08, with the labels that each got.

#1725 feature: agent、proxy安装增加数据压缩开关配置、节点探测默认关闭(closed #1664 closed #1707)
  frontend/src/config/config.ts
  frontend/src/i18n/en.js
  frontend/src/i18n/zh.js
  frontend/src/views/agent/agent-list.vue
  frontend/src/views/agent/components/create-excel.ts
  frontend/src/views/agent/components/parser-excel.vue
  frontend/src/views/agent/config/editTableConfig.ts
  frontend/src/views/agent/config/importTableConfig.js
  frontend/src/views/agent/config/setupTableConfig.ts
  frontend/src/views/cloud/cloud-manager-add/cloud-manager-preview.vue
  frontend/src/views/cloud/cloud-manager-add/cloud-manager-setup.vue
  frontend/src/views/cloud/cloud-manager-detail/cloud-detail-table.vue
  frontend/src/views/cloud/components/sideslider-content-edit.vue
  frontend/src/views/cloud/config/netTableConfig.ts
  frontend/src/views/cloud/config/proxy-detail-config.js
Labels: kind/feature

#1726 feature: 脱敏交互优化(closed #1650)
  frontend/src/common/regexp.ts
  frontend/src/components/common/verify-input.vue
  frontend/src/components/setup-table/install-input-type.vue
  frontend/src/components/setup-table/install-table.vue
  frontend/src/config/config.ts
  frontend/src/store/modules/config.ts
  frontend/src/types/config/config.ts
  frontend/src/views/agent/agent-setup/agent-import.vue
  frontend/src/views/agent/config/editTableConfig.ts
  frontend/src/views/cloud/components/sideslider-content-edit.vue
  frontend/src/views/cloud/components/sideslider-content.vue
  frontend/src/views/global-config/gse-config/set-access-point/step-host.vue
  frontend/src/views/global-config/gse-config/set-access-point/step-info.vue
Labels: kind/feature

#1727 feature: 任务历史支持IP过滤(closed #1631)
  frontend/src/common/util.ts
  frontend/src/views/task/task-list-filter.vue
  frontend/src/views/task/task-list.vue
Labels: kind/feature

#1729 sprintfix: 数据压缩 - 重载配置时附带数据压缩参数(closed #1664)
  frontend/src/views/agent/agent-list.vue
  frontend/src/views/agent/agent-setup/agent-import.vue
  frontend/src/views/cloud/cloud-manager-detail/cloud-detail-table.vue
  frontend/src/views/cloud/components/sideslider-content-edit.vue
Labels: kind/bug

#1731 sprintfix: 数据压缩 -修复proxy未解析参数问题 (closed #1664)
  frontend/src/store/modules/cloud.ts
Labels: kind/bug

#1748 feature: 移除 impacket 依赖 (closed #1747)
  .flake8
  ignorefile
  impacket/__init__.py
  impacket/crypto.py
  impacket/dcerpc/__init__.py
  impacket/dcerpc/v5/__init__.py
  impacket/dcerpc/v5/dcom/__init__.py
  impacket/dcerpc/v5/dcom/oaut.py
  impacket/dcerpc/v5/dcom/wmi.py
  impacket/dcerpc/v5/dcomrt.py
  impacket/dcerpc/v5/dtypes.py
  impacket/dcerpc/v5/enum.py
  impacket/dcerpc/v5/epm.py
  impacket/dcerpc/v5/ndr.py
  impacket/dcerpc/v5/rpch.py
  impacket/dcerpc/v5/rpcrt.py
  impacket/dcerpc/v5/transport.py
  impacket/examples/logger.py
  impacket/hresult_errors.py
  impacket/http.py
  impacket/krb5/__init__.py
  impacket/krb5/asn1.py
  impacket/krb5/ccache.py
  impacket/krb5/constants.py
  impacket/krb5/crypto.py
  impacket/krb5/gssapi.py
  impacket/krb5/kerberosv5.py
  impacket/krb5/pac.py
  impacket/krb5/types.py
  impacket/nmb.py
  impacket/nt_errors.py
  impacket/ntlm.py
  impacket/smb.py
  impacket/smb3.py
  impacket/smb3structs.py
  impacket/smbconnection.py
  impacket/smbserver.py
  impacket/spnego.py
  impacket/structure.py
  impacket/system_errors.py
  impacket/uuid.py
  impacket/version.py
  pack.sh
  pyproject.toml
  requirements.txt
Labels: pr/reviewable

#1744 bugfix: 项目启动卡住的问题 (fixed #1743)
  pipeline/component_framework/migrations/0007_auto_20230816_1537.py
  pipeline/component_framework/models.py
Labels: pr/reviewable

#1746 bugfix: 修复升级 Proxy 没能成功拉起 gse_agent 进程的问题 (fixed #1745)
  script_tools/gsectl/agent/linux/gsectl
  script_tools/gsectl/proxy/linux/gsectl
Labels: pr/reviewable

#1750 optimization: 注册 agent_id 重试机制 (closed #1609)
  script_tools/agent_tools/agent2/setup_agent.sh
  script_tools/agent_tools/agent2/setup_proxy.sh
Labels: pr/reviewable

#1755 feature: Proxy 安装适配 CentOS 8 / Ubuntu (closed #1405)
  script_tools/agent_tools/agent2/setup_proxy.sh
Labels: pr/reviewable

#1759 sprintfix: 国密变量统一
  .github/workflows/codecov.yml
  config/default.py
  env/__init__.py
  support-files/kubernetes/helm/bk-nodeman/templates/configmaps/env-configmap.yaml
  support-files/templates/nodeman#bin#environ.sh
Labels: pr/reviewable

#1761 sprintfix: 修复 yum 连接超时卡住安装流程的问题 (fixed #1405)
  script_tools/agent_tools/agent2/setup_proxy.sh
Labels: pr/reviewable

#1763 sprintfix: Proxy 导入时找不到依赖的 Agent 包 & 开启开发框架数据加密
  apps/backend/agent/artifact_builder/proxy.py
  config/default.py
  requirements.txt
Labels: pr/reviewable

#1772 bugfix: Agent管理 - 数据压缩属性未正确展示 (closed #1771)
  frontend/src/store/modules/agent.ts
Labels: pr/reviewable

#1788 feature: Agent 导入支持指定标签 (closed #1787)
  apps/backend/agent/artifact_builder/base.py
  apps/backend/management/commands/init_agents.py
  apps/backend/tests/agent/artifact_builder/enable_agent_pkg_manage/test_agent.py
  apps/backend/tests/agent/artifact_builder/enable_agent_pkg_manage/test_manage_commands.py
Labels: pr/reviewable
