Repository TencentBlueKing/bk-nodeman, pull requests merged in 2023-05, with the labels that each got.

#1538 feature: GSE 2.0 灰度切换过程中实时刷新 Agent / 插件状态 (closed #1537)
  apps/adapters/api/gse/v1.py
  apps/adapters/api/gse/v2.py
  apps/backend/subscription/tasks.py
  apps/core/gray/handlers.py
  apps/core/gray/tools.py
  apps/node_man/periodic_tasks/sync_agent_status_task.py
  apps/node_man/periodic_tasks/sync_proc_status_task.py
  apps/node_man/periodic_tasks/update_proxy_file.py
  apps/node_man/serializers/job.py
  apps/node_man/tests/test_pericdic_tasks/test_sync_agent_status_task.py
  apps/node_man/tests/test_pericdic_tasks/test_sync_proc_status_task.py
  support-files/kubernetes/helm/bk-nodeman/templates/ingress.yaml
  support-files/kubernetes/helm/bk-nodeman/values.yaml
Labels: kind/feature

#1539 sprintfix: 补充对订阅执行/重试接口的校验禁用规则
  apps/backend/subscription/handler.py
  apps/backend/subscription/tasks.py
  apps/backend/subscription/tools.py
  apps/backend/subscription/views.py
Labels: kind/bug

#1547 feature: 支持 GSE 2.0 证书密码文件配置 (closed #1546)
  apps/backend/agent/artifact_builder/agent.py
  apps/backend/agent/artifact_builder/base.py
  apps/backend/subscription/steps/agent_adapter/config_context/context_dataclass.py
  apps/backend/subscription/steps/agent_adapter/config_context/context_helper.py
  apps/node_man/constants.py
  support-files/kubernetes/helm/bk-nodeman/README.md
  support-files/kubernetes/helm/bk-nodeman/templates/configmaps/gse-cert-configmap.yaml
  support-files/kubernetes/helm/bk-nodeman/values.yaml
Labels: kind/feature

#1548 sprintfix: 修复 Agent 包注入依赖时未按预期跳过的问题 (fixed #1546)
  apps/backend/agent/artifact_builder/base.py
Labels: kind/bug

#1502 feat: 导航规范(closed #1501)
  frontend/index-dev.html
  frontend/index.html
  frontend/src/bk_icon_font/fonts/iconcool.eot
  frontend/src/bk_icon_font/fonts/iconcool.svg
  frontend/src/bk_icon_font/fonts/iconcool.ttf
  frontend/src/bk_icon_font/fonts/iconcool.woff
  frontend/src/bk_icon_font/style.css
  frontend/src/components/common/MixinsControlDropdown.vue
  frontend/src/components/common/footer.vue
  frontend/src/components/common/navigation.vue
  frontend/src/css/app.css
  frontend/src/i18n/en.js
  frontend/src/i18n/zh.js
  frontend/src/router/index.ts
  frontend/src/router/modules/global-config.ts
  frontend/src/setup/i18n-setup.ts
  frontend/src/views/agent/agent-setup/agent-import.vue
  frontend/src/views/cloud/cloud-manager-add/cloud-manager-add.vue
  frontend/src/views/cloud/cloud-manager-add/cloud-manager-setup.vue
  frontend/src/views/cloud/cloud-manager-detail/cloud-detail-table.vue
  frontend/src/views/plugin/plugin-list/plugin-list.vue
Labels: kind/feature

#1559 optimization: 减少异步任务执行结果消息在队列端积压 (#1588)
  apps/backend/subscription/tasks.py
Labels: kind/optimization

#1560 bugfix: 修复插件状态搜索存在 SQL 注入问题 (fixed #1556)
  .github/workflows/codecov.yml
  .github/workflows/python-app.yml
  app.yml
  apps/node_man/handlers/host.py
  docs/release.md
  release/V2.2.27_20220927.md
  support-files/kubernetes/helm/bk-nodeman/Chart.yaml
Labels: kind/bug

#1564 feat(front): 专有名词「云区域」调整为「管控区域」(closed #1545)
  frontend/src/components/common/navigation.vue
  frontend/src/components/common/strategy-table.vue
  frontend/src/components/ip-select-nm/static-content-table.vue
  frontend/src/components/ip-select-nm/static-content.vue
  frontend/src/components/ip-selector/business/topo-selector-new.vue
  frontend/src/components/ip-selector/business/topo-selector-nodeman.vue
  frontend/src/components/setup-table/install-table.vue
  frontend/src/i18n/en.js
  frontend/src/i18n/zh.js
  frontend/src/router/index.ts
  frontend/src/router/modules/cloud-manager.ts
  frontend/src/router/navigation-config.ts
  frontend/src/store/modules/agent.ts
  frontend/src/store/modules/cloud.ts
  frontend/src/store/modules/task.ts
  frontend/src/types/index.ts
  frontend/src/views/agent/agent-list.vue
  frontend/src/views/agent/agent-setup/agent-setup.vue
  frontend/src/views/agent/components/create-excel.ts
  frontend/src/views/agent/components/parser-excel.vue
  frontend/src/views/agent/config/editTableConfig.ts
  frontend/src/views/agent/config/importTableConfig.js
  frontend/src/views/cloud/cloud-manager-add/cloud-manager-add.vue
  frontend/src/views/cloud/cloud-manager-add/cloud-manager-preview.vue
  frontend/src/views/cloud/cloud-manager-detail/cloud-detail-nav.vue
  frontend/src/views/cloud/cloud-manager-detail/cloud-manager-detail.vue
  frontend/src/views/cloud/cloud-manager.vue
  frontend/src/views/cloud/config/proxy-detail-config.js
  frontend/src/views/plugin/plugin-list/plugin-list-operate.vue
  frontend/src/views/plugin/plugin-list/plugin-list-table.vue
  frontend/src/views/plugin/plugin-old/index.vue
  frontend/src/views/plugin/plugin-old/step-select-host.vue
  frontend/src/views/plugin/plugin-rule/plugin-rule-create/perform-preview.vue
  frontend/src/views/task/task-detail-table.vue
  frontend/src/views/task/task-detail.vue
  frontend/src/views/task/task-log.vue
Labels: kind/feature

#1565 sprintfix: 导航规范新增退出登陆接口 (closed #1501)
  frontend/src/components/common/navigation.vue
  frontend/src/types/index.ts
  frontend/src/vue-proto.d.ts
Labels: kind/bug
